### ISSUE TITLE
Uzip and Upload Online/Video Course Files for Job Search Fundamentals

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#100]
http://www.swiftintech.com/ecourses/essential-skills/jobsearch-skills/

Could you please unzip the ZIP file located at the below URL and upload all the files to the above directory:

http://coursesarticulate4x.s3.amazonaws.com/JobSearchFundamentals.zip

Please ping me on Facebook messenger or Skype the next time you are available for a chat. ;)

**Comment by farhany** [comment]
Completed. Sorry for the delay -- lots going on.

**Comment by msleeth2** [comment]
Thanks so much Farhan. No worries on how long you took getting to this. I can only imagine you've got a lot on your plate. I look forward to speaking sometime with you; whenever you feel like chatting. I'm available as always. Thx again!
