### ISSUE TITLE
Uzip and Upload Online/Video Course Files for Entering the Workforce

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#101]
http://www.swiftintech.com/ecourses/life-skills/employability-job-readiness2/

Could you please unzip the ZIP file located at the below URL and upload all the files to the above directory:

http://enterwork1018x.s3.amazonaws.com/Entertheworkforce.zip

Please ping me on Facebook messenger or Skype the next time you are available for a chat. ;)

**Comment by farhany** [comment]
Done.

**Comment by msleeth2** [comment]
Thank you sir!
