### ISSUE TITLE
Upload Files for Re-Entering the Workforce course

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#102]
Another course upload ticket to a slightly different system folder.

http://www.swiftintech.com/ecourses/life-skills/employability-job-readiness1/

Could you please unzip the ZIP file located at the below URL and upload all the files to the above directory:

http://reenterwork98dx.s3.amazonaws.com/re-enter-workforce.zip

**Comment by farhany** [comment]
Done

**Comment by msleeth2** [comment]
Really appreciate this, thanks!
