### ISSUE TITLE
Create Directory - Upload Files - for Essential Reading Skills Part 1 Course

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#103]
Similar tickets you've done in the past: #89 & #98

We've got a separate reading skills course called "Essential Reading Skills - Part 1" that we've never tracked course access for.

A. Could you please create a new folder in the "essential-skills" directory with the caption "reading-skills-part1" - i.e.

http://www.swiftintech.com/ecourses/essential-skills/reading-skills-part1/

B. Could you please upload the 1 PDF file accessible via the below URL to the above new directory folder you create:

http://nicecoursefiles98x.s3.amazonaws.com/ReadingSkills-P1-DL-v6.pdf

C. Could you also please unzip the ZIP file located at the below URL and upload all the files to the above directory:

http://essreadp1x8.s3.amazonaws.com/ReadingP1.zip

Please ping me on Facebook messenger or Skype the next time you are available for a chat. ;)

**Comment by farhany** [comment]
Done! Note, there is still a folder called "reading-skills" there, which I am sure you know about. I've left that there, obviously. Let me know *if* it needs to be removed.

**Comment by msleeth2** [comment]
I was literally just thinking about you...thinking you would get to this sometime this week or so. Uncanny!

Thanks so much!

P.S. Please leave the original "reading-skills" folder there for now. Thanks again.

Another ticket or two this month.

**Comment by msleeth2** [comment]
Unfortunately the files are not displaying for me. Would it be possible to double-check it?

**Comment by msleeth2** [comment]
My bad. It works for me.
