### ISSUE TITLE
Create Directory - Upload Files - for "MS Excel Fundamentals - Part 2" Course

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#104]
Similar tickets you've done in the past: #89, #98 & #103

We've got a separate MS Excel course called "MS Excel Fundamentals - Part 2" that we've never tracked course access for.

A. Could you please create a new folder in the "essential-skills" directory with the caption "msexcel-skills-part2" - i.e.

http://www.swiftintech.com/ecourses/essential-skills/msexcel-skills-part2/

B. Could you please upload the 1 PDF file accessible via the below URL to the above new directory folder you create:

http://nicecoursefiles98x.s3.amazonaws.com/MS_Excel_Fundamentals_Part-2_Slides.pdf

C. Could you also please unzip the ZIP file located at the below URL and upload all the files to the above directory:

http://msexcelp2abc9x.s3.amazonaws.com/MSExcel-P2.zip

Please ping me on Facebook messenger or Skype the next time you are available for a chat. ;)

**Comment by farhany** [comment]
Done. Will ping you when I'm free. 👍

**Comment by msleeth2** [comment]
Works for me. Thanks so much Farhan!
