### ISSUE TITLE
3 Updates on JobReady User Community Preview Page

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#105]
http://ew.swiftintech.com/community.html

![jobreadycommunitypage](https://cloud.githubusercontent.com/assets/7306437/25536597/6c256b80-2c09-11e7-8d34-1f141f608056.jpg)

The JobReady System User Environment's Community Website Preview Page needs 3 straightforward updates made to it as per below on or before May 12th, 2017.

A - Could you please change the text highlighted to read as follows:

Before entering the JobReady Online Community Network, please note you must agree to the community website's User Agreement outlined below. 

Please note you do not have to register on this community to access the content, but you must register if you want to participate. 

Your name (or a nickname), as well as your valid email address, would be required to register. You may also register with a social media profile (e.g. Facebook). 

Before registering for the community, you will be able to review the terms of service and privacy policy. Later, you can change your email address and add a photo of yourself, your location, and other information by clicking on the name link at the top right of the website. Your information will be used only by our support team and will not be shared or sold.

----

B - Could please remove the text and link "For a preview of the features of this community, click here."

----

C - For the "Continue" button, could you please change the website URL it links to:

From: 

https://getsatisfaction.com/jobready

To:

http://jobready.community/

----

P.S. To access this page as a user just to see this page in question, use these system access steps:

1. Go to http://ewjobready.com, click Agree, click User Login.

2. Enter User Name: jajatest4

3. Enter Password: abcdefg

**Comment by farhany** [comment]
Done!

**Comment by msleeth2** [comment]
Thanks!
