### ISSUE TITLE
Upload Files for Essential Interpersonal and Teamwork Skills Course

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#106]
http://www.swiftintech.com/ecourses/essential-skills/interpersonal-skills/

A. Could you please upload the 1 PDF file accessible via the below URL to the above directory folder:

http://nicecoursefiles98x.s3.amazonaws.com/Interpersonal-And-Teamwork-Skills-SL.pdf

B. Could you also please unzip the ZIP file located at the below URL and upload all the files to the above directory:

http://essinterperskills9.s3.amazonaws.com/Essential-Interpersonal.zip

**Comment by farhany** [comment]
Done.

**Comment by msleeth2** [comment]
Thanks so much!
