### ISSUE TITLE
Upload Files for Essential Reasoning Skills Course

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#107]
http://www.swiftintech.com/ecourses/essential-skills/reasoning-skills/

A. If it replaces a PDF file with the same name, that's fine...could you please upload the 1 PDF file accessible via the below URL to the above directory folder:

http://nicecoursefiles98x.s3.amazonaws.com/Essential-Reasoning-Skills-SL.pdf

B. Could you also please unzip the ZIP file located at the below URL and upload all the files to the above directory:

http://essreasonskills9x.s3.amazonaws.com/Essential-Reasoning.zip

**Comment by farhany** [comment]
Done

**Comment by msleeth2** [comment]
Thanks!
