### ISSUE TITLE
Create Directory - Upload Files - for Essential Reading Skills Part 2 Course

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#108]
Similar ticket: #98

We've got a separate reading skills course called "Essential Reading Skills - Part 2" that we've never tracked course access for.

A. Could you please create a new folder in the "essential-skills" directory with the caption "reading-skills-part2" - i.e.

http://www.swiftintech.com/ecourses/essential-skills/reading-skills-part2/

B. Could you also please upload the 1 PDF file accessible via the below URL to the above new directory folder you create:

http://nicecoursefiles98x.s3.amazonaws.com/Essential-Reading-Skills_P2_NICE_DL_v1.pdf

C. Finally, could you please unzip the ZIP file located at the below URL and upload all the files to the above directory:

http://essreadp2x9.s3.amazonaws.com/ReadingSkills-Part2.zip

**Comment by farhany** [comment]
Done.

**Comment by msleeth2** [comment]
Thanks so much Farhan. I just realized today that you got this done 9 days ago! I never received any notifications as to the ticket being closed and I think it must be just the email address I had associated to my Github profile up until this evening. I changed the email address to another better one of mine so I won't have this issue in future.
