### ISSUE TITLE
Upload Files for Essential Sales Skills Course

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#109]
http://www.swiftintech.com/ecourses/essential-skills/sales-skills/

A. If it replaces a PDF file with the same name that's fine...could you please upload the 1 PDF file accessible via the below URL to the above directory folder:

http://nicecoursefiles98x.s3.amazonaws.com/Essential-Sales-Skills-SL.pdf

B. Could you also please unzip the ZIP file located at the below URL and upload all the files to the above directory:

http://esaleskill9x.s3.amazonaws.com/EssentialSales.zip

**Comment by farhany** [comment]
Done, but I noticed the git repo which I religiously committed all these changes is no longer there? Know if anyone removed it or something?

**Comment by msleeth2** [comment]
I have no idea what a "git repo" is but it does not look like whatever you uploaded is showing up for users yet like it normally does. I can check with Darren but I don't expect to hear back anytime soon (unless I'm lucky). 

For example, the updated PDF (Essential-Sales-Skills-SL.pdf) that I had you upload is not showing up...but the old one is.

Is this a relatively straight forward fix to re-set up a "git repo" so that you can resume committing these changes to...for the purpose of having the updated file show up?

Or is this a major time consuming issue to resolve that I should check with Darren on?

N.B. I will certainly raise the issue with him of course...because this is interrupting your workflow, wasting our time etc.

**Comment by farhany** [comment]
Checking.

**Comment by farhany** [comment]
Weird, wierd, weird. 

I'll copy the files manually, but please ask Darren, why the 10.9.5.42 address is no longer working. Was that a VM that no longer exists? Can we update the IP from 10.9.5.42 to that of prod00? The workflow is prod00 is where you make changes, which are pulled into prod01 and prod01 every 5 minutes. Ask him if he removed the .git structure from ~/ce. It'll be a pain to re-add this into git, meaning the history will be lost, but that's fine.

My workflow is to copy to prod00. And there is an rsync script on prod01/02 that copies the data over from prod00. The script that does the copying is pointing to an IP address that is not responding (and not that of prod00). This is the command that runs every 5 minutes to copy the website static content:
*/5 * * * *    /home/admin/bin/prun /usr/local/admin/ce/bin/cron.sync_data

If you look in the script, it does a "rsync":

rsync -Hraz --delete admin@10.9.2.52:/usr/local/admin/ce/downloadable_files /usr/local/admin/ce

The IP address of 10.9.2.52 doesn't respond. What the hell happened here? Also the git repo, which has a copy of all source files plus my adds/tweaks are also not present on prod00:

What is missing below is the .git/ folder which tracks the changes and uploads them to github here: https://github.com/swiftinnovative/ce

admin@ip-10-85-57-111:~/ce$ ls -al
total 112
drwxr-sr-x 21 admin admin 4096 Dec 31  2009 .
drwxr-sr-x 11 admin admin 4096 Jan  2  2010 ..
-rw-r--r--  1 admin admin   29 Dec 15  2009 .cvsignore
drwxr-sr-x  6 admin admin 4096 Dec 31  2009 .svn
drwxr-sr-x  7 admin admin 4096 Dec 15  2009 FlexKiosk
drwxr-sr-x  5 admin admin 4096 Dec 15  2009 Jasper
-rw-r--r--  1 admin admin 2152 Dec 15  2009 Q9_TASKS

**Comment by farhany** [comment]
See my response.

Either I’m pulling a senior moment here, but I can’t get your site to show any page for http://www.swiftintech.com <http://www.swiftintech.com/>. Gets me blank page.

**Comment by msleeth2** [comment]
Hi Farhan,

It looks like what you updated the production system with was a version of the platform from 2009. Much of the functionality is no longer working (e.g. No Reports tab links in the admin environment and links on the user environment "Resources" tab that use an old domain no longer active.) 

The system is basically not usable in its current form unfortunately.

I will call you at 7:00 AM to see if I can catch you before you head off to work but if there's some easy way to get the most recent version of the system that was present before you did any of this work, let's move back to that. 

I obviously don't want to interrupt your full time job today and if you have to do this work this evening, I'll accept that.

In the event you can't get to this until after work today, I'll likely check with Darren to see if he can rectify this.

**Comment by msleeth2** [comment]
Further to my previous note, just an FYI that we've never had anything loaded at the root URL of http://www.swiftintech.com/. This is just the root domain behind which, I presume, everything is stored and displayed to users via "sub domains" (e.g. http://ew.swiftintech.com, http://jobsource.swiftintech.com, http://course-entry.swiftintech.com/ etc).

**Comment by msleeth2** [comment]
I notice the "Essential Sales Skills" course content was successfully uploaded. Thanks!

As such, I will soon close this ticket and we can correspond via email about the system issues we're currently experiencing.

**Comment by farhany** [comment]
Closing.
