### ISSUE TITLE
3 Link Updates in the EW JobReady System

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#111]
Hi Farhan,

I have 3 important link updates for you found within the Experience Works JobReady System. I'll write you a separate email about this too. 

Here are the link updates:

<b>Number 1:</b>

Administrator Environment Dashboard Tab - "JobReady tutorials and important files" link

System Page Location: http://ew.admin.swiftintech.com/tt/be/main/dashboard

When administrators login to the admin Dashboard by going to ewjobready.com, clicking Admin Login and then logging in (e.g. your admin ID/password is: farhan99 / splunk99), they'll see a link called "JobReady tutorials and important files". Currently that link forwards people to this URL: http://jobreadydocmod2x.s3.amazonaws.com/engage.swf

Could you please change the URL that should load in a new browser window to be:

http://ewjobready.com/JobReady-Administrator-Resources-Within-System.html

******************

<b>Number 2:</b>

User Environment "Help" tab button.

System Page Location: http://ew.swiftintech.com/tt/fe/main/dashboard

When a user logs into the JobReady system user environment by going to ewjobready.com, clicking User Login and then logging in
(sample user name and password is: jajatest4 / abcdefg), they'll see a series of tab buttons at the top of their page (e.g. "Dashboard", "Skill Inventory" etc). At the end is a green tab called "Help". Currently when users click that "Help" tab, a new smaller than full browser window opens and loads this URL: http://ewhelpsystem4dx.s3.amazonaws.com/interaction_html5.html

Could you please change the URL that should <b>now load in a new maximized window</b> to be:

http://ewjobready.com/JobReady-Help-Within-System.html

******************

<b>Number 3:</b>

User Environment - "Additional Learning Opportunities" link found on the "Resources" page.

System Page Location: http://ew.swiftintech.com/resources.html

When a user logs into the JobReady system user environment by going to ewjobready.com, clicking User Login and then logging in (sample user name and password is: jajatest4 / abcdefg) and then clicking the "Resources" tab; they will see a link under the "Useful Resources" section called "Additional Learning Opportunities". Currently, when users click that link, a new browser window opens and loads this URL: 
http://addlearnoppsv2x.s3.amazonaws.com/player.html

Could you please change the URL that should load in a new browser window to be:

http://ewjobready.com/Additional-Learning-Within-System.html

******************

**Comment by farhany** [comment]
All three links changed. Please verify.

**Comment by msleeth2** [comment]
Yup! They all work. Thanks so much!
