### ISSUE TITLE
Text/Link Updates in JobSource System

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#113]
http://jobsource.swiftintech.com/

Similar Ticket: #111

Hi Farhan,

I have 5 important link/text updates for you found within the JobSource System that Easter Seals uses. I'll write you a separate email about this too.

N.B. While the JobSource system is located at http://jobsource.swiftintech.com/, please note I have registered a similar looking domain name:

http://jobsource-swiftintech.com/

Notice the "-" in between jobsource and swiftintech in my set-up URL vs the "." used in the JobSource System URL you work with. This new domain has been set-up for hosting resource web pages that are external to the JobSource system. In registering this domain name, I didn't want users to notice too much that the various web pages they are linking to from JobSource are actually not within the JobSource system.

Here are the 4 link updates and one text update:

Number 1 Link Update:

Administrator Environment Dashboard Tab - "Documentation, tutorials and important files" link

System Page Location: http://jobsource.admin.swiftintech.com/tt/be/main/dashboard

When administrators login to the admin Dashboard by going to esnycareerfinder.com, clicking Agree, then Administrator Login and then logging in (e.g. my admin ID/password is: msleeth / arturs32), they'll see a link called "Documentation, tutorials and important files". Currently trys to open a SWF file in a new window. 

Could you please change the URL that should load in a new browser window to be:

http://jobsource-swiftintech.com/Administrator-Resources-Within-System.html

*****

Number 2 Link Update:

User Environment "Help" tab button.

System Page Location: http://jobsource.swiftintech.com/tt/fe/main/dashboard

When a user logs into the JobSource system user environment by going to esnycareerfinder.com, clicking Agree, then User Login and then logging in
(sample user name and password is: jajatest / abcdefg), they'll see a series of tab buttons at the top of their page (e.g. "Dashboard", "Skill Inventory" etc). At the end is a green tab called "Help". Currently when users click that "Help" tab, a new smaller than full browser window opens and loads a SWF file.

Could you please change the URL that should now load in a new maximized window to be:

http://jobsource-swiftintech.com/Help-Within-System.html

*****

Number 3 Link Update:

User Environment - "Additional Learning Opportunities" link found on the "Resources" page.

System Page Location: http://jobsource.swiftintech.com/resources.html

When a user logs into the JobSource system user environment by going to esnycareerfinder.com, clicking Agree, then User Login, then logging in
(sample user name and password is: jajatest / abcdefg), and then clicking the "Resources" tab; they will see a link under the "Useful Resources" section called "Additional Learning Opportunities". Currently, when users click that link, a new browser window opens and loads this URL:
http://addlearnoppsv2x.s3.amazonaws.com/player.html

Could you please change the URL that should load in a new browser window to be:

http://jobsource-swiftintech.com/Additional-Learning-Within-System.html

*****

Number 4 Text Update:

User Environment - "Courses from NBSA" text found on the "Resources" page.

System Page Location: http://jobsource.swiftintech.com/resources.html

When a user logs into the JobSource system user environment by going to esnycareerfinder.com, clicking Agree, then User Login, then logging in
(sample user name and password is: jajatest / abcdefg), and then clicking the "Resources" tab; they will see text under the "Courses" section called "Courses from NBSA".

Could you please change the text to instead read: 

"Courses from the National Institute of Continuing Education:"

*****

Number 5 Link Update:

User Environment - "Search for a Course" link found on the "Resources" page.

System Page Location: http://jobsource.swiftintech.com/resources.html

When a user logs into the JobSource system user environment by going to esnycareerfinder.com, clicking Agree, then User Login, then logging in
(sample user name and password is: jajatest / abcdefg), and then clicking the "Resources" tab; they will see a link under the "Courses" section, "Courses from the Skill Improvement Course Library:" subsection called "Search for a Course". Currently, when users click that link, it loads this URL:
http://jobsource.nbsalliance.com/tt/fe/course/search?csearch_src_id=CESIL

Could you please change the URL that should load in the same window to be:

http://jobsource.swiftintech.com/tt/fe/course/search?csearch_src_id=CESIL

**Comment by farhany** [comment]
Done. Please verify.

**Comment by farhany** [comment]
Git log:

commit 639e1565ff0dfe8dc4d02ced489ee6af9ceb1cd1
Author: admin <admin@prod00.(none)>
Date:   Sun Feb 4 05:07:14 2018 +0000
    Ticket 113 - Update links and text

**Comment by msleeth2** [comment]
You got all of them except for Number 2 :(

**Comment by msleeth2** [comment]
Number 2 Link Update:

User Environment "Help" tab button.

System Page Location: http://jobsource.swiftintech.com/tt/fe/main/dashboard

When a user logs into the JobSource system user environment by going to esnycareerfinder.com, clicking Agree, then User Login and then logging in
(sample user name and password is: jajatest / abcdefg), they'll see a series of tab buttons at the top of their page (e.g. "Dashboard", "Skill Inventory" etc). At the end is a green tab called "Help". Currently when users click that "Help" tab, a new smaller than full browser window opens and loads a SWF file.

Could you please change the URL that should now load in a new maximized window to be:

http://jobsource-swiftintech.com/Help-Within-System.html

**Comment by msleeth2** [comment]
P.S. I appreciate your hard work as always! Thanks!

**Comment by farhany** [comment]
Oh noes... I'll fix it up shortly. :)

**Comment by farhany** [comment]
Added final change to previous commit:
commit ef61ae522a69d9f92dca90c7eba67be6714dcde0
Author: admin <admin@prod00.(none)>
Date:   Sun Feb 4 05:07:14 2018 +0000
    Ticket 113 - Update links and text

**Comment by msleeth2** [comment]
Thanks so much Farhan!

All good!
