### ISSUE TITLE
JobSource System - Orientation button and Resources Page Updates

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#114]
http://jobsource.swiftintech.com/resources.html

Sample Demo Login Details:

http://jobsource.swiftintech.com/tt/fe/main/login

User Name: jajatest

Password: abcdefg

---------------------------------------------------------------------

A few more URL, link and text updates for the JobSource system.

1. Two Link Updates on the Resources Page.

Links should open in a new window and load different URLs as follows:

a) Under the "CareerFinder Resources" section, you'll see the "Course Catalog" link. Could you please have clicking on this link opening a new window?

b) For "a" above, could we please have the URL that loads in the new window be as follows instead:

http://nationalice.org/course-catalog.html

c) Under the "CareerFinder Resources" section, you'll see the "Certification Catalog" link. Could you please have clicking on this link opening a new window?

d) For "c" above, could we please have the URL that loads in the new window be as follows instead:

http://nationalice.org/certification-catalog.html

---------------------------------------------------------------------

2. New dynamic icon and link on Resources page:

In the "Courses" section, under the "Courses from the Skill Improvement Course Library:" heading and above the "Search for a Course" link, could you please:

a) Add a new blue question mark icon and associated link with caption "Get help finding a Course".

![gethelpfindingacourse](https://user-images.githubusercontent.com/7306437/35937564-8747b012-0c14-11e8-9e9d-21ad9e77424d.png)

b) Have it so that clicking on this new blue question mark icon displays the following text underneath the link caption (just like the other question mark icons function):

"Clicking here will allow you to write to us for additional assistance in the event you cannot find a particular course."

c) When the "Get help finding a Course" link is clicked, a new pop-up window should open. The URL that should load in this pop-up window should be:

http://jobsource-swiftintech.com/get-help-finding-a-course.html

Note this above URL is for the website I maintain (notice the dash in it > http://jobsource-swiftintech.com/).

It should not be a maximized window that opens for C above but just a pop-up. As for the dimensions, I'm not sure of what they should be exactly. What I can say is that the same link on http://ew.swiftintech.com/resources.html# produces a pop-up window that has perfect dimensions. If you had the dimensions at the same size as the pop-up that displays when "Additional Learning Opportunities" on this Resources page is clicked, that's fine too.

---------------------------------------------------------------------

http://jobsource.swiftintech.com/tt/fe/

3. Change to the URL that loads in a new window:

![orientation](https://user-images.githubusercontent.com/7306437/35937576-9122126c-0c14-11e8-9e89-d0d9ddb12ea3.png)

For the green "Orientation" button at the top of the user environment, clicking on it opens a new window and loads URL:

http://estutorial3x.s3.amazonaws.com/player.html

I need this above URL that loads to be changed to the following URL instead:

http://jobsource-swiftintech.com/orientation.html

**Comment by msleeth2** [comment]
If it's possible for this to get done this month, that would be appreciated. No pressure, no rush if you can't though.

**Comment by farhany** [comment]
Done.

**Comment by msleeth2** [comment]
Thank you so much Farhan. All work well. Now I'm off to Punta Cana with the wife and kids! Talk to you when I get back!
