### ISSUE TITLE
Upload Updated Course Files for Re-Entering the Workforce course

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#116]
Related Ticket: #102

http://www.swiftintech.com/ecourses/life-skills/employability-job-readiness1/

Could you please:

Unzip the ZIP file located at the below URL and upload all the files to the above directory:

http://reenterwork98dx.s3.amazonaws.com/Re-Enter-v2.zip

**Comment by farhany** [comment]
Done

**Comment by msleeth2** [comment]
Thanks, I didn't see this until just now. No notifications from Github. Must check my spam.
