### ISSUE TITLE
Upload Files for Essential Medical Office Skills - Part 1 Course

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#120]
http://www.swiftintech.com/ecourses/essential-skills/medicaloffice-skills/

A. Could you please upload the 1 PDF file accessible via the below URL to the above directory folder:

http://nicecoursefiles98x.s3.amazonaws.com/Essential-Medical-Office-Skills-SL-P1.pdf

B. Could you also please unzip the ZIP file located at the below URL and upload all the files to the above directory:

http://essmedoff9x.s3.amazonaws.com/MedOfficeSkillsCourseP1.zip

**Comment by farhany** [comment]
Mark, the first PDF link is bad. It's an empty file. Can you fix it? See below:

-rw-r--r--  1 admin admin       0 Sep 21 02:36 Essential-Medical-Office-Skills-SL-P1.pdf
-rw-r--r--  1 admin admin 6290480 Feb 18  2016 Essential-Medical-Office-Skills-SL.pdf
-rw-r--r--  1 admin admin 1102822 Feb 18  2016 Essential-Medical-Office-Skills.pdf

I've unzipped the other part.

**Comment by msleeth2** [comment]
Sorry about that. Here's an updated file link:

http://nicecoursefiles98x.s3.amazonaws.com/MedOffP1.pdf

I tested this one. It works.

**Comment by farhany** [comment]
Done.

**Comment by msleeth2** [comment]
Thanks!
