### ISSUE TITLE
Search for Openings page fails to load

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#121]
http://ew.swiftintech.com/tt/fe/job/display

On the Job Display Pages in the User Environment, a click on "Search for Openings" fails to load the job search engine links page.

The page tries to load and then an error "failure to load" type page results.

We of course should no longer have the job feed being involved in the system at all and affecting this page.

A user you can test with:

1. Go to http://ewjobready.com, click Agree, click User Login.

2. Enter User Name: jajatest4

3. Enter Password: abcdefg

Click any job title on the Dashboard page. Then click "Search for Openings" as per the below screen shot.

![searchforopenings](https://user-images.githubusercontent.com/7306437/47252463-8f649180-d413-11e8-8e21-11dbad4b5391.png)

**Comment by dji-wgames** [comment]
fixed

**Comment by msleeth2** [comment]
Confirmed fixed. Thanks!
