### ISSUE TITLE
Upload Updated Files for the Entering the Workforce course

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#123]
Related Ticket: #117

http://www.swiftintech.com/ecourses/life-skills/employability-job-readiness2/

Could you please:

Unzip the ZIP file located at the below URL and upload all the files to the above directory:

http://enterwork1018x.s3.amazonaws.com/EnteringWorkforce.zip

**Comment by farhany** [comment]
Marc, I noticed that while I add everything to git after making a change, I could not push the changes to the github repo. I get a weird error now:

admin@prod00:~/ecourses/life-skills$ git push
no kex alg
fatal: The remote end hung up unexpectedly

Anyhow, this is done:
admin@prod00:~/ecourses/life-skills$ git log
commit 5c9cd09272318236fb162dbc21d561bf81eda882
Author: admin <admin@prod00.(none)>
Date:   Wed Apr 24 19:43:52 2019 +0000

    Added EnteringWorkforce.zip contents to employability-job-readiness2 - Issue 123

**Comment by msleeth2** [comment]
Eek.

OK. I may have to follow-up with Darren on this tonight from the looks of it. 

Just tied up now. Sorry. Thanks for looking at this!

**Comment by farhany** [comment]
So the ssh client is severely outdated that's why it doesn't work... It's from 2006ish.

**Comment by msleeth2** [comment]
As per my comment on the other ticket, I'll definitely follow-up with Darren on this. The insight about the SSH client being from 2006ish is appreciated. I'll mention it to him and hopefully he can resolve this. I'll let you know!

**Comment by msleeth2** [comment]
Hi Darren,

As per the commentary from Farhan on this ticket, he can't seem to finish the upload of the standard Articulate course files we've been using for years...because, as he says it, the "ssh client is severely outdated."

He's included the error message he gets above. 

Any chance you can look into finishing off this ticket - i.e. the upload of the course files to the requested course folder?

**Comment by farhany** [comment]
Files were uploaded to the web server locations, it's just that any commits I make I cannot push to Github which would be really good if you every wanted to roll back a change/upload.

**Comment by dji-wgames** [comment]
These servers are so old!  I suppose if need be, we could setup a free tier instance, and push to github from there.

**Comment by msleeth2** [comment]
Oy yoy. 

I would not know where to begin of course.

As I'm not seeing the updated course files when I try and launch the course from the user side, I am presuming that this issue at hand for you both is the cause.

I'll wait to hear more on this from you when you have some time.

**Comment by farhany** [comment]
Hmm... You're not seeing the files? Hmm... They were uploaded to the right location on prod00. I'll take a look.

**Comment by farhany** [comment]
The files are definitely rsync'd over to prod01... 02... 

Same contents. Example:

prod00:
admin@prod00:/usr/local/admin/ce/html/ecourses/life-skills$ ls -al
total 40
drwxr-sr-x 10 admin admin 4096 Apr 24 19:42 .
drwxr-sr-x  8 admin admin 4096 Feb 17  2016 ..
drwxr-sr-x  4 admin admin 4096 Aug 26  2018 employability-job-readiness1
**drwxr-sr-x  4 admin admin 4096 Apr 24 19:42 employability-job-readiness2**
drwxr-sr-x  2 admin admin 4096 Mar 16  2016 living-with-technology
drwxr-sr-x  4 admin admin 4096 Mar 15  2016 money-management1
drwxr-sr-x  4 admin admin 4096 Mar 29  2016 money-management2
drwxr-sr-x  4 admin admin 4096 Feb 19  2016 personal-health-management
drwxr-sr-x  3 admin admin 4096 Dec 14  2015 telework
drwxr-sr-x  3 admin admin 4096 Dec 14  2015 x

prod01:
admin@prod01:/usr/local/admin/ce/html/ecourses/life-skills$ ls -al
total 40
drwxr-sr-x 10 admin admin 4096 Apr 24 19:42 .
drwxr-sr-x  8 admin admin 4096 Feb 17  2016 ..
drwxr-sr-x  4 admin admin 4096 Aug 26  2018 employability-job-readiness1
**drwxr-sr-x  4 admin admin 4096 Apr 24 19:42 employability-job-readiness2**
drwxr-sr-x  2 admin admin 4096 Mar 16  2016 living-with-technology
drwxr-sr-x  4 admin admin 4096 Mar 15  2016 money-management1
drwxr-sr-x  4 admin admin 4096 Mar 29  2016 money-management2
drwxr-sr-x  4 admin admin 4096 Feb 19  2016 personal-health-management
drwxr-sr-x  3 admin admin 4096 Dec 14  2015 telework
drwxr-sr-x  3 admin admin 4096 Dec 14  2015 x
admin@prod01:/usr/local/admin/ce/html/ecourses/life-skills$

Someone who knows about how the links to the content works would need to look at why the content isn't visible.

**Comment by msleeth2** [comment]
Sorry for taking too long to get back to you on this. Didn't see the last message. I'd be the guy who knows how the links to the content work.

What I see, is the old content. The course file that loads is the old one (C) 2016. 

What would be interesting is to delete out the existing course files from:

http://www.swiftintech.com/ecourses/life-skills/employability-job-readiness2/

Then let me know so I can confirm that nothing loads on the link click.

Then once I confirm that, I'd ask you to add the new content that is in the ZIP file:

http://enterwork1018x.s3.amazonaws.com/EnteringWorkforce.zip

Then we'd see if the new course file loads.

**Comment by msleeth2** [comment]
Hello Darren and Farhan,

Just an FYI that the updated course files for this particular course are now available to system participants. 

Thanks so much for all your work on this ticket.

Ticket closed!
