### ISSUE TITLE
Upload Updated Files for Job Search Fundamentals course

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#124]
Related Ticket: #117

http://www.swiftintech.com/ecourses/essential-skills/jobsearch-skills/

Could you please:

Unzip the ZIP file located at the below URL and upload all the files to the above directory:

http://jobsearchfunx4x.s3.amazonaws.com/JobSearchFun.zip

**Comment by farhany** [comment]
Done, please verify

**Comment by msleeth2** [comment]
Thanks, I'll take a look as soon as I can this evening.

**Comment by msleeth2** [comment]
I see that the updated files from the ZIP provided to you are not showing up for live users - so I guess the error you noticed from the other ticket is to blame. I'll follow-up with Darren on this. Thanks for your efforts here!

**Comment by msleeth2** [comment]
Hi Darren,

As per the commentary from Farhan ticket #123 , he can't seem to finish the upload of the standard Articulate course files on this ticket that we've been using for years...because, as he says it, the "ssh client is severely outdated."

He's included the error message he gets on ticket #123 

Any chance you can look into finishing off this ticket - i.e. the upload of the course files to the requested course folder?

**Comment by msleeth2** [comment]
Hello Darren and Farhan,

Just an FYI that the updated course files for this particular course are now available to system participants. 

Thanks so much for all your work on this ticket.

Ticket closed!
