### ISSUE TITLE
Estimate on how long to Undelete an EW User Record ?

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#125]
Hello Darren,

Eileen deleted a user record by mistake.

Is there any way for you to get it back for her? If so, how long would it take you to do this you think? 30 minutes? 3 hours?

Just looking for any estimate of your time at this point.

I seem to recall Jodi may have done this years ago but I can't remember now. If you can't get back the user record with everything that was on it (e.g. IEP records), I'm not sure what value there is to get it back.

I still see the record in question within MGMT. The system user ID is: 7551717150

The user name on it is: Eburrows

N.B. So as not to confuse you, Eileen re-created a user account for Elsie Burrows with a similar user name (just a lower case first letter): eburrows

**Comment by dji-wgames** [comment]
So, the record still exists in mgmt, but the user can't login?

**Comment by msleeth2** [comment]
![CantLogin](https://user-images.githubusercontent.com/7306437/55892374-3e448780-5b84-11e9-89f7-dcb9f8288242.png)

Correct - because the record was deleted by Eileen via the Admin system. Above is what I get when I try and login using the person's login credentials.

The nice thing is - the user no longer needs this record - because they are no longer with EW. Eileen just needs it for audit/record keeping purposes I guess.

**Comment by dji-wgames** [comment]
Ok, can you log in now?

**Comment by msleeth2** [comment]
No,

I still get the same message - and this user still does not show up in a search from within the admin system. I have tried more than 3 times to login and usually after the 3rd try, the error message changes to something like "Your account is now inactive".

**Comment by dji-wgames** [comment]
ok, can log in now

**Comment by dji-wgames** [comment]
does it show up in admin?

**Comment by msleeth2** [comment]
Yes!

Awesome man!

Eileen will be thrilled!

Thanks!
