### ISSUE TITLE
Create Directory - Upload Files - for "MS Word Fundamentals - Part 1" Course

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#127]
Similar tickets you've done in the past: #89, #98, #103 & #104

I'll send you an email related to this ticket later today.

We've got a new and separate MS Word course called "MS Word Fundamentals - Part 1" that we'd like to publish and have never tracked course access for.

A. Could you please create a new folder in the "essential-skills" directory with the caption "msword-skills-part1" - i.e.

http://www.swiftintech.com/ecourses/essential-skills/msword-skills-part1/

B. Could you please upload the 1 PDF file accessible via the below URL to the above new directory folder you create:

http://nicecoursefiles98x.s3.amazonaws.com/MS-Word-Course-Slides-P1.pdf

C. Could you also please unzip the ZIP file located at the below URL and upload all the files to the above directory:

http://mswordp15x.s3.amazonaws.com/MSWord-P1.zip

Please ping me on Facebook messenger or Skype the next time you wanna chat. ;)

**Comment by farhany** [comment]
Done!

**Comment by msleeth2** [comment]
Thanks Farhan,

I notice though that the course file seems to revert to the old NBSAlliance.com URL that is lurking somewhere in the back end. I think we've faced this issue in the past and Darren helped us out.

To test the issue:

1. Go to http://ewjobready.com. Click Agree. Click User Login.

2. Enter User Name: jajatest4

3. Enter Password: abcdefg

4. Once logged in, click Resources. Click Essential Skills. Click "Take Course" for MS Word Fundamentals and you will see a new window opens and the existing course file loads OK.

5. However, while still logged in...you can close that new window that opened...and since you're still logged in where the "Launch Course" link is, copy/paste the following URL which SHOULD refer to the new path and course file:

https://www.swiftintech.com/ecourses/essential-skills/msword-skills-part1/presentation.html?userid=7551727990&crs_id=10134353&tt_code=EW&str=U2FsdGVkX1%2BFhEqBOCDSofabMRfixC0sybKYNzW49xH%2BjlxLHpHR1GRfueLrpLiaIsfpQ6PCCAifNzgSjs41MRZB%2FD2R2CpXhN3rzGoz%2FvOIii0BRUvMRoq6jzmm%2BahjfjWQcgo6kyY%3D

See how what loads go to weird websites? This is because the nbsalliance.com URL that the system used to use is owned by others (spoofers and other nefarious types I guess). But for some reason...the NBSAlliance.com URL still plays a role somewhere deep in our code.

**Comment by msleeth2** [comment]
I will look a bit more at this tonight FYI. Got to spend some time with the kids now. :P

**Comment by msleeth2** [comment]
Great success!

I see the course is now working. Thanks Farhan!

Ticket closed!
