### ISSUE TITLE
Upload Updated Files - for "MS Word Fundamentals - Part 1" Course

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#128]
I'll send you an email related to this ticket soon.

The MS Word course called "MS Word Fundamentals - Part 1" had to be re-published without Flash traces since Flash won't work anymore in browsers at year end. 

http://www.swiftintech.com/ecourses/essential-skills/msword-skills-part1/

A. Could you please remove all the files currently in the above directory.

B. Could you please upload the 1 PDF file accessible via the below URL to the above directory:

http://nicecoursefiles98x.s3.amazonaws.com/MS-Word-Course-Slides-P1.pdf

C. Could you please unzip the ZIP file located at the below URL and upload all the files to the above directory:

http://mswordp15x.s3.amazonaws.com/MSWord-P1.zip

Please ping me on Facebook messenger or Skype the next time you wanna chat. ;)

**Comment by farhany** [comment]
Done

**Comment by msleeth2** [comment]
Thanks Farhan!
