### ISSUE TITLE
Create Directory - Upload Files - for "MS Word Fundamentals - Part 2" Course

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#129]
Similar tickets you've done in the past: #127

We've got a new and separate MS Word course called "MS Word Fundamentals - Part 2" that we'd like to publish and have never tracked course access for.

A. Could you please create a new folder in the "essential-skills" directory with the caption "msword-skills-part2" - i.e.

http://www.swiftintech.com/ecourses/essential-skills/msword-skills-part2/

B. Could you please upload the 1 PDF file accessible via the below URL to the above new directory folder you create:

http://nicecoursefiles98x.s3.amazonaws.com/MSWord-P2.pdf

C. Could you also please unzip the ZIP file located at the below URL and upload all the files to the above directory:

http://mswordq16x.s3.amazonaws.com/MSWord-P2.zip

Please ping me on Facebook messenger or Skype the next time you wanna chat. ;)

**Comment by farhany** [comment]
Also done.

**Comment by msleeth2** [comment]
Thanks Farhan!
