### ISSUE TITLE
Upload Updated Files for Essential Customer Service Skills Course

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#131]
Related Ticket #55

http://www.swiftintech.com/ecourses/essential-skills/customerservice-skills/

A. Could you please upload the one updated PDF file accessible via the below URL to the above directory folder:

http://nicecoursefiles98x.s3.amazonaws.com/Essential-Customer-Service-SL.pdf

B. Could you also please unzip the ZIP file located at the below URL and upload all the files to the above directory:

http://esscustx3x8.s3.amazonaws.com/Ess-Customer-Skills.zip

**Comment by farhany** [comment]
Same here, moved old files to old/. 

New:

admin@prod00:~/ecourses/essential-skills/customerservice-skills$ ls -al
total 40884
drwxr-sr-x  6 admin admin     4096 Sep 30 14:17 .
drwxr-sr-x 30 admin admin     4096 Aug 23 02:18 ..
-rw-r--r--  1 admin admin 35082530 Sep 23 18:54 Ess-Customer-Skills.zip
-rw-r--r--  1 admin admin  6632867 Aug  5 06:34 Essential-Customer-Service-SL.pdf
drwxr-xr-x  4 admin admin     4096 Sep 23 00:05 html5
-rw-r--r--  1 admin admin      799 Sep 22 23:47 meta.xml
drwxr-xr-x  5 admin admin    20480 Sep 23 00:05 mobile
drwxr-sr-x  4 admin admin     4096 Sep 30 14:17 old
-rw-r--r--  1 admin admin    11504 Sep 23 00:05 presentation.html
drwxr-xr-x  4 admin admin    16384 Sep 23 00:05 presentation_content
-rw-r--r--  1 admin admin    18450 Sep 23 00:05 presentation_html5.html

Let me know if I can remove old/ dir.

**Comment by msleeth2** [comment]
You can remove the old/ directory that has any old files... sure.

**Comment by farhany** [comment]
Done
