### ISSUE TITLE
Upload Updated Files for Essential Medical Office Skills - Part 1 Course

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#132]
Related Ticket #120

http://www.swiftintech.com/ecourses/essential-skills/medicaloffice-skills/

A. Could you please upload the one updated PDF file accessible via the below URL to the above directory folder:

http://nicecoursefiles98x.s3.amazonaws.com/Essential-Medical-Office-Skills-SL-P1.pdf

B. Could you also please unzip the ZIP file located at the below URL and upload all the files to the above directory:

http://essmedoff9x.s3.amazonaws.com/UpMedOfficeSkillsCourseP1.zip

**Comment by farhany** [comment]
Cleaned up what was in the ecourses/essential-skills/medicaloffice-skills/ dir, and made a backuo in old/.

New:
admin@prod00:~/ecourses/essential-skills/medicaloffice-skills$ ls -al
total 52940
drwxr-sr-x  6 admin admin     4096 Sep 30 14:14 .
drwxr-sr-x 30 admin admin     4096 Aug 23 02:18 ..
-rw-r--r--  1 admin admin  7903888 Sep  6 23:46 Essential-Medical-Office-Skills-SL-P1.pdf
drwxr-xr-x  4 admin admin     4096 Sep 17 08:48 html5
-rw-r--r--  1 admin admin      802 Sep 17 02:24 meta.xml
drwxr-xr-x  4 admin admin    20480 Sep 17 08:49 mobile
drwxr-sr-x  5 admin admin     4096 Sep 30 14:14 old
-rw-r--r--  1 admin admin    11511 Sep 17 08:49 presentation.html
drwxr-xr-x  4 admin admin    20480 Sep 17 08:49 presentation_content
-rw-r--r--  1 admin admin    18464 Sep 17 08:49 presentation_html5.html

Can I remove old/? Which contains:

admin@prod00:~/ecourses/essential-skills/medicaloffice-skills$ ls -al old
total 75792
drwxr-sr-x 5 admin admin     4096 Sep 30 14:14 .
drwxr-sr-x 6 admin admin     4096 Sep 30 14:14 ..
-rw-r--r-- 1 admin admin  6290480 Feb 18  2016 Essential-Medical-Office-Skills-SL.pdf
-rw-r--r-- 1 admin admin  1102822 Feb 18  2016 Essential-Medical-Office-Skills.pdf
-rw-r--r-- 1 admin admin 23450304 Oct 11  2018 MedOffP1.pdf
-rw-r--r-- 1 admin admin     5496 Sep 25  2018 amplaunch.html
-rw-r--r-- 1 admin admin      804 Sep 25  2018 meta.xml
drwxr-xr-x 4 admin admin    65536 Sep 25  2018 mobile
drwxr-sr-x 2 admin admin     4096 Sep 30 14:12 old
-rw-r--r-- 1 admin admin     4144 Sep 25  2018 presentation.html
-rw-r--r-- 1 admin admin   345095 Sep 25  2018 presentation.swf
drwxr-xr-x 4 admin admin    49152 Sep 25  2018 presentation_content
-rw-r--r-- 1 admin admin     5152 Sep 25  2018 presentation_html5.html
-rw-r--r-- 1 admin admin      366 Feb 24  2017 presentation_unsupported.html

**Comment by msleeth2** [comment]
All the old stuff that you listed can be removed. Thanks!

**Comment by farhany** [comment]
Done
