### ISSUE TITLE
Error Message On Start Here Job Match Click

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#134]
https://ew.swiftintech.com/tt/fe/main/dashboard

My demo user gets an error message when "Start Here!" is clicked on the Dashboard.

To recreate:

1. Go to http://ewjobready.com/
2. Click Agree.
3. Click User Login.
4. Enter User Name: jajatest4
5. Enter Password: abcdefg
6. Click Login.
7. Click Start Here
8. Receive Error Message

Could you please fix? 

Thanks!

**Comment by dji-wgames** [comment]
fixed

**Comment by msleeth2** [comment]
Thanks
