### ISSUE TITLE
Transfer of System from Akaibo Amazon Account to SWIFT Amazon Account

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#24]
This ticket is to make note of the activities and development hours required to transition the prod and dev environments from Akaibo's Amazon Account to the SWIFT Amazon Account.

**Comment by msleeth2** [comment]
Account ID: 270581712268
User Name: vince_rivera@experienceworks.org
Password: Be$wift100M

Please note that you need to Login to the root.

**Comment by msleeth2** [comment]
Whether you do this first or #3, I'll leave it up to you. ;)

**Comment by msleeth2** [comment]
Looks like this ticket is done. But you did spend time on mopping up the SWIFT Amazon account (admin@beswift.com) so that it doesn't have any more monthly charges on it. 

For accounting against the 70 hours EW paid for, how many hour(s) did you spend shutting off services, reducing the SWIFT Amazon account costs to zero etc?

**Comment by msleeth2** [comment]
Looks like this ticket is done. But you did spend time on mopping up the SWIFT Amazon account (admin@beswift.com) so that it doesn't have any more monthly charges on it.

For accounting against the 70 hours EW paid for, how many hour(s) did you spend shutting off services, reducing the SWIFT Amazon account costs to zero etc?

**Comment by lamenyq** [comment]
It wasn't just mopping up.  We were going to use this account, so some time was spent on that before we decided to shut it down.

10 hours with the above in mind.
