### ISSUE TITLE
Change SubDomain URLs from NBSA to SWIFTINTECH.COM for various systems.

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#3]
Akaibo Ticket: 343

As part of the re-branding of NBSA system properties acquired by SWIFT, the subdomains of nbsalliance.com need to be changed to swiftintech.com, a domain SWIFT has registered at GoDaddy. It's not hosted anywhere yet.

So, as part of this change, ew.nbsalliance.com needs to be changed to ew.swiftintech.com for example.

It is understood that after implementing this change, SWIFT would have unrestricted access to all the assets/collateral of the systems (e.g. NBSA course source files, PDF files, images, text etc).

To the knowledge of SWIFT, this root domain change will be implemented on the URLs noted below.

Experience Works:

**http://ew.nbsalliance.com/**

**http://ew.admin.nbsalliance.com/**

**http://ewl.nbsalliance.com/**

National Council on Aging:

**http://ncoa.nbsalliance.com/**

**http://ncoa.admin.nbsalliance.com/**

**http://ncoajobsource.nbsalliance.com/**

AARPF:

**http://aarpworksearch.nbsalliance.com/**

**http://aarpworksearch.admin.nbsalliance.com/**

**http://wsl.nbsalliance.com/**

**http://is.nbsalliance.com/**

JobSource:

**http://jobsource.nbsalliance.com/**

**http://jobsource.admin.nbsalliance.com/**

Misc.

**http://course-entry.nbsalliance.com/**

**http://mgmt.nbsalliance.com:4101/**

**http://workandlearn.nbsalliance.com/**

**http://pme.nbsalliance.com/**

**http://castategov.business.nbsalliance.com/**

**Comment by msleeth2** [comment]
Whether you do this first or #24 , I'll leave it up to you. ;)

**Comment by msleeth2** [comment]
Whether you do this first or #24 , I'll leave it up to you. ;)

**Comment by msleeth2** [comment]
I've **bolded** the URLs in the description that have had a swiftintech.com equivalent created for them so far.

**Comment by msleeth2** [comment]
Almost done.

I still notice we don't have swiftintech URLs for:

http://jobsource.admin.nbsalliance.com/

http://ncoajobsource.nbsalliance.com/

**Comment by msleeth2** [comment]
Thanks for all the work here. Looks like we're done on this item. If you could please make note on this ticket of how many hours were spent setting up all these swiftintech.com sub-domains, I can mark it down on our tracking file for Sally.

**Comment by msleeth2** [comment]
Thanks for all the work here. Looks like we're done on this item. If you could please make note on this ticket of how many hours were spent setting up all these swiftintech.com sub-domains, I can mark it down on our tracking file for Sally.

**Comment by lamenyq** [comment]
16 hours.
