### ISSUE TITLE
Misc Rebranding Updates for SWIFT Sites

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#38]
Pre-requisite Ticket: #3

**A - Footer Copyright Updates:**

Please change the following:

"©2009 National Business Services Alliance, a division of CE Technologies, Inc. All rights reserved."

OR

"2009 CE Technologies, Inc. All rights reserved."

TO:

"©2016 SWIFT Innovative Technologies, LLC. All rights reserved."...

...for the following websites:

http://ew.admin.swiftintech.com/

http://ncoa.swiftintech.com/

Code found in Github via:  ce/html/sites/ncoa/standard/footer.html

http://ncoa.admin.swiftintech.com/

Code found in Github via:  ce/html/sites/ncoa.admin/standard/footer.html

http://jobsource.admin.swiftintech.com/

http://aarpworksearch.admin.swiftintech.com/

http://wsl.swiftintech.com/

Code found in Github via: ce/html/sites/wsl/standard/footer.html

http://is.swiftintech.com/

http://ewl.swiftintech.com

> Screenshot of where code is to update this:
> http://nicemisfiles48dx.s3.amazonaws.com/EWL-SiteFooterCode.png

http://ncoajobsource.swiftintech.com/

**B - NBSA Logo Removal:** (You don't need to replace the NBSA logo with anything for this item)

i) http://wsl.swiftintech.com/ (top left corner)

ii) http://wsl.swiftintech.com/tt/wsl/main/welcome (top left corner)

iii) http://ewl.swiftintech.com/  (top left corner)

iv) http://aarpworksearch.admin.swiftintech.com/ (bottom right corner)

v) http://is.swiftintech.com/ (top left corner)

vi) http://is.swiftintech.com/tt/ne/main/welcome (top left corner)

**C - Course Provider - NBSA Logo Replacement:**

For the NBSA logo you have at, for example:
http://ncoa.swiftintech.com/courseprovider/logos/SM-NBSAE.gif
http://ew.swiftintech.com/courseprovider/logos/SM-NBSAE.gif
http://jobsource.swiftintech.com/courseprovider/logos/SM-NBSAE.gif
etc

Could you please change it to this logo:

http://nicemisfiles48dx.s3.amazonaws.com/NICE-Course-Provider-Logo.jpg

**Comment by msleeth2** [comment]
Assigning this to you now Farhan. 

It's important this please gets done before the end of the year if at all possible.

Thanks!

**Comment by farhany** [comment]
Completed.
