### ISSUE TITLE
Communication Failure Error Message on View User Click of SWIFTinTECH Admin Sites

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#39]
Admins get a "Communication Failure" when clicking the "View User" icon on the SWIFTinTECH admin sites.
1. Go to http://ncoa.admin.swiftintech.com/.
2. Login as an admin with this admin ID/password: msleeth/arturs32
3. Look-up user name: jajatest
4. Click the "View User" icon and you'll get the "Communication Failure" pop-up window:

![communicationfailure](https://cloud.githubusercontent.com/assets/7306437/9648788/5462ae34-51ba-11e5-8ead-dab092275d40.png)

Notes:

a) I apologize for saying the re-direct was active on the NCOA admin side. I was wrong.

b) This occurs on http://ew.admin.swiftintech.com as well and I would assume all other admin sites.

**Comment by lamenyq** [comment]
This was very much related to noca.admin not being 1) redirected, and 2) defined as swiftintech.com in the mgmt tool.

It's understood, so it won't be an issue when we bring the others over.

**Comment by msleeth2** [comment]
Great. Thanks. I tested NCOA.admin and it works OK now. Ticket closed.

P.S. I will file a ticket for work tracking/hours reporting purposes related to the re-direct set-ups as well.
