### ISSUE TITLE
Sub-Domain NBSAlliance.com to SWIFTinTECH.com Re-Direct Set-Ups

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#40]
Let's set-up URL re-directs for each SWIFT system and SWIFT client user/admin system; two-by-two just to ensure everything is OK with each before moving on to the next.

http://ncoa.nbsalliance.com to http://ncoa.swiftintech.com

http://ncoa.admin.nbsalliance.com to http://ncoa.admin.swiftintech.com

The above two are done now. I will post the next 2 in a subsequent posting to this ticket when I'm ready to test them.

**Comment by msleeth2** [comment]
http://ew.nbsalliance.com redirecting to http://ew.swiftintech.com

http://ew.admin.nbsalliance.com redirecting to http://ew.admin.swiftintech.com

If you can please let me know once that is done, I'll get the EW skin site updated.

**Comment by msleeth2** [comment]
Thanks for EW. Next on the list is AARPF:

http://aarpworksearch.nbsalliance.com/ redirecting to http://aarpworksearch.swiftintech.com/

http://aarpworksearch.admin.nbsalliance.com/ redirecting to http://aarpworksearch.admin.swiftintech.com/

If you can please let me know once that is done, I'll get the AARPF skin site updated.

**Comment by msleeth2** [comment]
Thanks for doing these 2 today:

http://jobsource.nbsalliance.com to http://jobsource.swiftintech.com

http://jobsource.admin.nbsalliance.com to http://jobsource.admin.swiftintech.com

**Comment by msleeth2** [comment]
To finish this ticket off, we'll need the following two re-directs set-up:

http://wsl.nbsalliance.com/ to http://wsl.swiftintech.com/

http://ewl.nbsalliance.com/ to http://ewl.swiftintech.com/

P.S. The other URLs set-up with swiftintech.com sub-domains don't need re-directs set-up.

**Comment by lamenyq** [comment]
Why don't they need redirects?  The database still thinks they are nsballiance.com, so there are motions I need to go through with each site.  This redirect provides a nice checklist.

**Comment by msleeth2** [comment]
Ok sure, re-directs for all. Thx!
