### ISSUE TITLE
Delete NBSA Course PDF Files

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#41]
Hi Farhan,

Your first ticket from me! ;)

So, in order for the contractual obligations to be satisfied, one thing we have to do is rid the system of all things NBSA branded. Much work has been done so far but the major piece is removing the NBSA branded course files from the 2 places Darren showed us. The first place is from within this path found via Github:

ce / html / course / files /

So all the PDFs from this location can be deleted.

[NBSA-Course-Files-Deletion-Related.pdf](https://github.com/swiftinnovative/projectkickoff/files/31908/NBSA-Course-Files-Deletion-Related.pdf)

As per the attached, I went ahead and deleted (via GitHub) the "LifeSkills-Living_with_Technology_Color.pdf course guide file. I "committed" this change to "master" via GitHub which I trust I was supposed to do as one part of the deletion process.

<b>If you would like me to go ahead and delete every other PDF from this network path in GitHub, please let me know.</b>

After you have advised me to do that and after I have completed the deletion, I trust from our call with Darren there is one more thing via that command line interface he showed us that has to be done to delete these files.

Could you please let me know how we should proceed to make this happen?

P.S. FYI, I will be able to tell this deletion was successful once a click on the Living with Technology course guide link (from within the user interface) results in an error message of a file not being found. I will then update the link in the Learning Management System.

**Comment by farhany** [comment]
Can you tell me quickly where this file resides in terms of the URL?

If not, I'll dig and find it. And then I'll let you know how to do this in terms of the git pull on the server. Cool?

**Comment by msleeth2** [comment]
Sure,

From the user side, the link to this file tells me it is located at:

http://www.swiftintech.com/course/files/LifeSkills-Living_with_Technology_Color.pdf

I'm sure you'll notice all the other NBSA branded course PDF files in that /course/files/ location. They all need to be deleted of course...and if I can make your life easier by deleting them via GitHub and then having you finish the job on your end, then I'm ready to do that.

**Comment by msleeth2** [comment]
One important note for the time being:

Please do not delete PDF files that have the prefix "ESP" (e.g. ESP_StudyGuide_CustomerServiceBasics.pdf). I'm still trying locate the "Course Display" pages for the Spanish courses.

I'll get back to you ASAP once I've located them.

**Comment by msleeth2** [comment]
If you'd like to give another try at deleting a course file, there is the following PDF file for the MS Word course called "StudyGuide_MSWord.pdf" and it is at the path below:

http://www.swiftintech.com/course/files/StudyGuide_MSWord.pdf

In other news, for the Spanish course files (pre-fixed with "ESP", again please keep them for now. I am speaking with someone on Monday who can share more insight on where the "course display pages" are for these courses. Once I have control over those course display pages and have advised, we can proceed to remove these "ESP" prefixed PDF files.

**Comment by farhany** [comment]
File removed: html/course/files/StudyGuide_MSWord.pdf

**Comment by msleeth2** [comment]
OK, you now have the all clear to delete all PDF files from within the directory:

http://www.swiftintech.com/course/files/

I will file another ticket relating to the upload of new PDF files that can go in this directory.

**Comment by farhany** [comment]
I can't seem to log in to the above link, I get a forbidden page.

Anyhow, these are the pages on prod00, can you pick up what you want removed? I know you don't want ESP\* removed, but they're listed below anyway for sake of completeness:

html/course/files:
Accounting_Bookkeeping_Fundamentals_Handbook_color.pdf
Basic Sales Skills_Handbook_color.pdf
Basic_Customer_Service_Skills_Handbook_color.pdf
Basic_Time_Management_Skills_Handbook_color.pdf
Computer_Skills_Study_Guide_BW.pdf
Customer_Service_Skills_Course_Handbook_BW.pdf
Customer_Service_Skills_Course_Handbook_Color.pdf
Customer_Service_Skills_StudyGuide_BW.pdf
Drug_Dosage_and_Therapy.pdf
ESP_Basic_Customer_Service_Skills_Handbook_color.pdf
ESP_StudyGuide_ComputerSkillsBasics.pdf
ESP_StudyGuide_ComputerSkillsBasics_BW.pdf
ESP_StudyGuide_CustomerServiceBasics.pdf
ESP_StudyGuide_CustomerServiceBasics_BW.pdf
ESP_StudyGuide_InterpersonalTeamworkBasics.pdf
ESP_StudyGuide_InterpersonalTeamworkBasics_BW.pdf
ESP_StudyGuide_JobSearchFundamentals.pdf
ESP_StudyGuide_MSWordBasics.pdf
ESP_StudyGuide_MSWordBasics_BW.pdf
ESP_StudyGuide_MathBasics.pdf
ESP_StudyGuide_MathBasics_BW.pdf
ESP_StudyGuide_OfficeSkillsBasics.pdf
ESP_StudyGuide_OfficeSkillsBasics_BW.pdf
ESP_StudyGuide_ReadingComprensionBasics.pdf
ESP_StudyGuide_ReadingComprensionBasics_BW.pdf
ESP_StudyGuide_ReasoningSkillsBasics.pdf
ESP_StudyGuide_ReasoningSkillsBasics_BW.pdf
ESP_StudyGuide_TelephoneSkillsBasics.pdf
ESP_StudyGuide_TelephoneSkillsBasics_BW.pdf
ESP_StudyGuide_TimeManagementBasics.pdf
ESP_StudyGuide_TimeManagementBasics_BW.pdf
ESP_WorkSearch_User_Manual.pdf
ESP_WorkSearch_User_Manual_BW.pdf
ESP_Workplace_Computer_Skills_Handbook_color.pdf
ESP_Workplace_Telephone_Skills_Handbook_color.pdf
Effective_Business_Communications_Course_Handbook_BW.pdf
Effective_Business_Communications_Course_Handbook_Color.pdf
Effective_Business_Communications_Handbook_color.pdf
Employablity_Job_Readiness_bw.pdf
Employablity_Job_Readiness_color.pdf
Entering_the_Workforce_bw.pdf
Entering_the_Workforce_color.pdf
Essential_Bookkeeping_Skills_Guide_BW.pdf
Interpersonal_Communication_Course_Handbook_BW.pdf
Interpersonal_Communication_Course_Handbook_Color.pdf
Interpersonal_Communication_and_Teamwork_Skills_Handbook_color.pdf
Interpersonal_Teamwork_Skills_StudyGuide_BW.pdf
Interviewing_Fundamentals_Handbook_color.pdf
Interviewing_Fundamentals_Module3_BW.pdf
JobReady_Program_Admin_Manual.pdf
JobReady_Program_User_Manual.pdf
Job_Search_Fundamentals_Handbook_color.pdf
Job_Search_Fundamentals_Module2_BW.pdf
LifeSkills-Living_with_Technology_BW.pdf
LifeSkills-Personal_and_Health_Management_BW.pdf
LifeSkills-Personal_and_Health_Management_Color.pdf
Marketing_Fundamentals_Course_Handbook_BW.pdf
Marketing_Fundamentals_Course_Handbook_Color.pdf
Marketing_Fundamentals_Handbook_color.pdf
Math Skills_StudyGuide_BW.pdf
Medical_Office_Skills_StudyGuide_BW.pdf
Microsoft_Excel_Study_Guide_BW.pdf
Microsoft_Word_Study_Guide.pdf
Microsoft_Word_Study_Guide_BW.pdf
MoneyManagementPart1_bw.pdf
MoneyManagementPart1_color.pdf
MoneyManagementPart2_bw.pdf
MoneyManagementPart2_color.pdf
Office_Skills_Study_Guide_BW.pdf
Pharmaceutical_Calculations.pdf
Pharmacology_Math_For_the_Practical_Nurse.pdf
Prescription_Interpretation.pdf
Reading_and_Comprehension_Skills_Guide_BW.pdf
Reasoning_Skills_StudyGuide_BW.pdf
Resume_Fundamentals_Handbook_color.pdf
Resume_Fundamentals_Module1_BW.pdf
SMCEEWS_sm.gif
Sales_Skills_Study_Guide_BW.pdf
Selling_Techniques_Course_Handbook_BW.pdf
Selling_Techniques_Course_Handbook_Color.pdf
Selling_Techniques_Handbook_color.pdf
StudyGuide-computerbasics1.pdf
StudyGuide_AccountingBookkeeping.pdf
StudyGuide_AnalyticalThinking.pdf
StudyGuide_BasicOffice.pdf
StudyGuide_BasicSales.pdf
StudyGuide_BasicTelephone.pdf
StudyGuide_Computerbasics.pdf
StudyGuide_CustomerService.pdf
StudyGuide_InterpersonalTeamwork.pdf
StudyGuide_InterviewingFundamentals.pdf
StudyGuide_JobSearchFundamentals.pdf
StudyGuide_MSExcel.pdf
StudyGuide_MathNumeracy.pdf
StudyGuide_MedicalOffice.pdf
StudyGuide_ReadingComprension.pdf
StudyGuide_ResumeFundamentals.pdf
StudyGuide_TeleworkFundamentals.pdf
StudyGuide_TimeManagement.pdf
Taking_Vital_Signs.pdf
Telephone_Skills_Study_Guide_BW.pdf
Therapeutics_I.pdf
Therapeutics_II.pdf
Therapeutics_III.pdf
Therapeutics_IV.pdf
Therapeutics_V.pdf
Time_Management_Skills_Study_Guide_BW.pdf
Time_and_Priority_Management_Course_Handbook_BW.pdf
Time_and_Priority_Management_Course_Handbook_Color.pdf
Time_and_Priority_Management_Handbook_color.pdf
WorkSearch_User_Manual.pdf
Workplace_Computer_Skills_Handbook_color.pdf
Workplace_Telephone_Skills_Handbook_color.pdf

**Comment by msleeth2** [comment]
You are now welcome to delete everything in that folder, including the ESP\* pre-fixed files. 

Not sure about what is going on with the link you are referring to, but I will soon test out each of the ZIP file links if those are what don't work. Thx!

**Comment by msleeth2** [comment]
Further to my last post, the PDFs you have listed are of course in the same location as the MS Word and Living with Technology PDFs that you previously successfully deleted...so I apologize if the link I provided does not work and for any confusion caused. I trust you can delete these PDF files. If not, let's discuss.

P.S. Ticket #44 has the re-branded PDF files you can upload to the same location and this upload will need to be done right after you complete this #41 ticket. Thx.

**Comment by farhany** [comment]
Closing, *.pdfs removed.
