### ISSUE TITLE
Upload NICE Course PDF Files

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#44]
Pre-requisite Ticket:  #41 

http://www.swiftintech.com/course/files/

Once ticket #41 is done, could you please unzip and upload all the PDFs found via the below links to the above noted directory?

The password for all below links is <b>courses88</b>

NICE Course Slides:

https://freshmoremediainc.box.com/s/he4z38r7swclx7bldrqjkf6xwvib0b0j

NICE Course Guides:

https://freshmoremediainc.box.com/s/hgql6sazb1ueu1nnyl6cpcr3rfom2bse

NICE Course Guides (Spanish):

https://freshmoremediainc.box.com/s/quclcpaofqh57bsoz7xfgh7bu9hwcbx7

**Comment by farhany** [comment]
Uploaded new PDFs.
