### ISSUE TITLE
Removal of NBSA Brand Loose Ends - Batch 2

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#46]
<b>A - Course Provider - NBSA Logo Replacement:</b>

For the NBSA logo you have at:
http://ncoa.swiftintech.com/courseprovider/logos/SM-NBSAA.gif
http://ew.swiftintech.com/courseprovider/logos/SM-NBSAA.gif
http://jobsource.swiftintech.com/courseprovider/logos/SM-NBSAA.gif
etc

Could you please replace it with this logo of the same file name:

http://nicemisfiles48dx.s3.amazonaws.com/SM-NBSAA.gif

<b>B - Job Display Page Text Updates:</b>

For the 3 client systems at:

http://ew.swiftintech.com/tt/fe/job/display
http://ncoa.swiftintech.com/tt/fe/job/display
http://jobsource.swiftintech.com/tt/fe/job/display

![jobdisplaypage](https://cloud.githubusercontent.com/assets/7306437/11630513/037f6284-9ccc-11e5-9d41-c36838330a83.gif)

As per the above screen shot, could you please:

` 1. Change the tool tip text the user sees when mousing over the "Certifications" link from:

"If you are awarded an NBSA certification for this job, the certification will be titled: [Job Title Variable] Certification"

TO:

"If you are awarded a certification for this job, the certification will be titled: [Job Title Variable] Certification"

` 2. Change the text "<b>Note:</b> The NBSA Certification that will be granted for this job is:"

TO:

"<b>Note:</b> The certification that will be granted for this job is the:

<b>C - NBSA Logo Replacements</b>

With the replacement logo located here:

http://nicemisfiles48dx.s3.amazonaws.com/NBSA-logo.gif

Could you please save over the NBSA logos you have located here:

http://ew.swiftintech.com/images/NBSA-logo.gif

http://aarpworksearch.swiftintech.com/help/NBSA-logo.gif

<b>D - CE Technologies Logo Replacement</b>

i) With the replacement logo located here:

http://nicemisfiles48dx.s3.amazonaws.com/tklogo.gif

Could you please save over the CE Tech logo you have located here:

http://jobsource.swiftintech.com/images/tklogo.gif

ii) With the replacement logo located here:

http://nicemisfiles48dx.s3.amazonaws.com/mgmt_title.gif

Could you please save over the CE Tech logo you have located here:

http://mgmt.swiftintech.com:4101/mgmt/images/mgmt_title.gif

<b>E - NBSA Branded PDF File Replacements</b>

i) With the replacement file located here:

http://nicemisfiles48dx.s3.amazonaws.com/Interpreting_Job_Matches.pdf

Could you please save over the NBSA branded PDF file you have located here:

http://aarpworksearch.swiftintech.com/assets/Interpreting_Job_Matches.pdf

ii) With the replacement file located here:

http://nicemisfiles48dx.s3.amazonaws.com/Interpreting-My-Job-Match-Results_NCOA.pdf

Could you please save over the NBSA branded PDF file you have located here:

http://ncoa.swiftintech.com/assets/Interpreting-My-Job-Match-Results_NCOA.pdf

**Comment by farhany** [comment]
Completed.
