### ISSUE TITLE
Changing text CE Technologies Inc to SWIFT Innovative Technologies LLC

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#47]
On the "Important Information" (a.k.a. index.html) pages of each client system (both English and Spanish versions), we need to change all instances of the text <b>CE Technologies Inc</b> to <b>SWIFT Innovative Technologies LLC</b>.

This would be for the following client system pages:

<b>Experience Works JobReady: </b>

http://ew.swiftintech.com/index.html

http://ew.swiftintech.com/index-es.html

http://ewl.swiftintech.com/index.html

<b>NCOA JobSource: </b>

http://ncoa.swiftintech.com/index.html

http://ncoa.swiftintech.com/index-es.html

http://ncoajobsource.swiftintech.com/index.html

<b>TK JobSource that SETA and ESNY use: </b>

http://jobsource.swiftintech.com/index.html

http://jobsource.swiftintech.com/index-es.html

<b>AARP Foundation WorkSearch (No Spanish Available): </b>

http://aarpworksearch.swiftintech.com/index.html

http://wsl.swiftintech.com/index.html

http://is.swiftintech.com/index.html

**Comment by farhany** [comment]
This is complete.
