### ISSUE TITLE
Duplicate EW JobReady Resources Page Retirement

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#48]
Duplicate EW Resources Page Elimination:

![demoresourcespage](https://cloud.githubusercontent.com/assets/7306437/11665025/1f611a50-9db3-11e5-9c21-483ca947ae9e.png)

The page at http://ew.swiftintech.com/demo.resources.html is the most up-to-date and is kind of a near duplicate of what is at:

http://ew.swiftintech.com/resources.html

Legacy developer Jodi I guess created demo.resources.html for some reason a few years ago and ended up using this page instead of the original resources.html page. In doing so, he created some complications that now need to be resolved.

We are going to keep resources.html and eventually retire demo.resources.html

Steps to complete:

' 1. Could you please save over the resources.html file with all that you have at demo.resources.html?

Taking care of the above item will ensure both the demo.resources.html and the resources.html pages look and act the same.

' 2. Aside from "Help" and "Logout", the main navigation bar consists of "Dashboard", "Skill Inventory", "Test Inventory", "Learning Plan", "Edit Account" and "Resources". When on each of these pages, a click on "Resources" will send the user to: 

http://ew.swiftintech.com/demo.resources.html

Could you please make it so that when "Resources" is clicked, no matter what page you are on, it will send the user to:

http://ew.swiftintech.com/resources.html

' 3. After making the above changes and implementing them, please <b>do not</b> delete the demo.resources.html page yet. I would like to keep it for the time being just to ensure I haven't missed anything. Another ticket will be filed to update what you should now have at resources.html after completing this ticket.

**Comment by farhany** [comment]
Step 1 done.

**Comment by farhany** [comment]
Step 2 done.

**Comment by farhany** [comment]
Step 3 - N/A. File not removed.
