### ISSUE TITLE
Removal of NBSA Brand Loose Ends - Batch 3

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#49]
<b>'1  - EW Text Updates</b>

A) EW Certification Request Preview Page:

http://ew.swiftintech.com/tt/fe/job/cert_info

![certrequestinfopage](https://cloud.githubusercontent.com/assets/7306437/11664907/558aa732-9db2-11e5-8534-37ecbb2f7fb3.png)

i) Could you please change:

"Please be advised that you have 2 options. Certifications issued to you that are branded by NBSA are free of charge. However, there would be a fee of $500 required if you wish to receive a certification branded by a NBSA university collaborator."

TO:

"Please be advised that certifications issued to you will be branded by the <b>National Institute of Continuing Education</b>. It is free to receive them and they will only be sent to you by email. As such, it is important that your email address on the "Edit Account" page is accurate."

---

ii) Could you please change:

"to inquire and/or purchase your certification."

TO:

"to request your certification."

---

B) EW Certification Request Confirmation Page:

http://ew.swiftintech.com/tt/fe/job/cert_request

![certrequestconfirmationpage](https://cloud.githubusercontent.com/assets/7306437/11664942/8e720f04-9db2-11e5-8ae3-e2e5c0855160.png)

i) Could you please change:

"We require some additional information to process your request. Fill out the form below and press Continue. We will get back to you in 24-48 hours."

TO:

"Click the Continue button to confirm and submit your request."

---

ii) Please <b>keep</b> the "Continue" button. However, could you please remove the "Email", "Phone" and "Comments" fields. They are no longer needed and people waste their time filling them out.

---

iii) Could you please change the text:

"The NBSA Certification that will be granted for this job is"

TO:

"The title on the certification you are requesting will be:"

---

iv) Could you please change:

"Please be advised that you have 2 options. Certifications issued to you that are branded by NBSA are free of charge. However, there would be a fee of $500 required if you wish to receive a certification branded by a NBSA university collaborator."

TO:

"Please be advised that certifications issued to you will be branded by the <b>National Institute of Continuing Education</b>. It is free to receive them and they will only be sent to you by email. As such, it is important that your email address on the "Edit Account" page is accurate."

---

<b>'2  - NCOA Text Updates</b>

A) NCOA Certification Request Preview Page:

http://ncoa.swiftintech.com/tt/fe/job/cert_info

i) Could you please change:

"If you choose to be certified for any of your job choices, please be advised that there is a payment required to purchase and receive your official certification. Certification fees start at $500 and go higher depending on the job/certification choice."

TO:

"Please be advised that certifications issued to you will be branded by the <b>National Institute of Continuing Education</b>. It is free to receive them and they will only be sent to you by email. As such, it is important that your email address on the "Edit Account" page is accurate."

---

ii) Could you please change:

"to inquire and/or purchase your certification."

TO:

"to request your certification."

---

B) NCOA Certification Request Confirmation Page:

http://ncoa.swiftintech.com/tt/fe/job/cert_request

i) Could you please change:

"We require some additional information to process your request. Fill out the form below and press Continue. We will get back to you in 24-48 hours."

TO:

"Click the Continue button to confirm and submit your request."

---

ii) Please <b>keep</b> the "Continue" button. However, could you please remove the "Email", "Phone" and "Comments" fields. They are no longer needed and people waste their time filling them out.

---

iii) Could you please change the text:

"The NBSA Certification that will be granted for this job is"

TO:

"The title on the certification you are requesting will be:"

---

iv) Could you please change:

"If you choose to be certified for any of your job choices, please be advised that there is a payment required to purchase and receive your official certification. Certification fees start at $500 and go higher depending on the job/certification choice."

TO:

"Please be advised that certifications issued to you will be branded by the <b>National Institute of Continuing Education</b>. It is free to receive them and they will only be sent to you by email. As such, it is important that your email address on the "Edit Account" page is accurate."

---

<b>'3  - TurnKey (TK) JobSource Text Updates</b>

A) Certification Request Preview Page:

http://jobsource.swiftintech.com/tt/fe/job/cert_info

i) Could you please change:

"If you choose to be certified for any of your job choices, please be advised that there is a payment required to purchase and receive your official certification. Certification fees start at $500 and go higher depending on the job/certification choice."

TO:

"Please be advised that certifications issued to you will be branded by the <b>National Institute of Continuing Education</b>. It is free to receive them and they will only be sent to you by email. As such, it is important that your email address on the "Edit Account" page is accurate."

---

ii) Could you please change:

"to inquire and/or purchase your certification."

TO:

"to request your certification."

---

B) Certification Request Confirmation Page:

http://jobsource.swiftintech.com/tt/fe/job/cert_request

i) Could you please change:

"We require some additional information to process your request. Fill out the form below and press Continue. We will get back to you in 24-48 hours."

TO:

"Click the Continue button to confirm and submit your request."

---

ii) Please <b>keep</b> the "Continue" button. However, could you please remove the "Email", "Phone" and "Comments" fields. They are no longer needed and people waste their time filling them out.

---

iii) Could you please change the text:

"The NBSA Certification that will be granted for this job is"

TO:

"The title on the certification you are requesting will be:"

---

iv) Could you please change:

"If you choose to be certified for any of your job choices, please be advised that there is a payment required to purchase and receive your official certification. Certification fees start at $500 and go higher depending on the job/certification choice."

TO:

"Please be advised that certifications issued to you will be branded by the <b>National Institute of Continuing Education</b>. It is free to receive them and they will only be sent to you by email. As such, it is important that your email address on the "Edit Account" page is accurate."

**Comment by farhany** [comment]
This should be complete, please verify.

**Comment by msleeth2** [comment]
http://jobsource.swiftintech.com/tt/fe/job/cert_request

![jobsource-cert_request-page](https://cloud.githubusercontent.com/assets/7306437/13230679/529abaf0-d974-11e5-8607-dac7fbc55fd9.png)

For 3/B/iii, I notice we need to change the text:

"The NBSA Certification that will be granted for this job is"

TO:

"The title on the certification you are requesting will be:"

**Comment by msleeth2** [comment]
For 3/A/i and 3/B/iv, could you please left justify the new text?

Currently they are both centered.

**Comment by msleeth2** [comment]
http://ncoa.swiftintech.com/tt/fe/job/cert_request

For 2/B/iii, I notice we need to change the text:

"The NBSA Certification that will be granted for this job is"

TO:

"The title on the certification you are requesting will be:"

**Comment by msleeth2** [comment]
For 2/A/i and 2/B/iv, could you please left justify the new text?

Currently they are both centered.

**Comment by msleeth2** [comment]
Whenever you have some time this month, we just have 4 small follow-ups left as per above.

**Comment by farhany** [comment]
Sure, no worries.

**Comment by farhany** [comment]
I haven't changed any alignment. And looked in 1 place, it is already left-aligned. A bit confused.

**Comment by msleeth2** [comment]
Thanks for your work on this. Going to close the ticket and then file any loose end items in other tickets.
