### ISSUE TITLE
Delete Files for NBSA Online Courses

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#50]
Could you please delete all the NBSA course files found within the following directories:

' 1. http://www.swiftintech.com/ecourses/essential-skills/bookkeeping-skills/

' 2. http://www.swiftintech.com/ecourses/essential-skills/customerservice-skills/

' 3. http://www.swiftintech.com/ecourses/essential-skills/interpersonal-skills/

' 4. http://www.swiftintech.com/ecourses/essential-skills/math-skills/

' 5. http://www.swiftintech.com/ecourses/essential-skills/medicaloffice-skills/

' 6. http://www.swiftintech.com/ecourses/essential-skills/office-skills/

' 7. http://www.swiftintech.com/ecourses/essential-skills/reading-skills/

' 8. http://www.swiftintech.com/ecourses/essential-skills/reasoning-skills/

' 9. http://www.swiftintech.com/ecourses/essential-skills/sales-skills/

' 10. http://www.swiftintech.com/ecourses/essential-skills/telephone-skills/

' 11. Time Management Skills:
http://www.swiftintech.com/ecourses_open/essential-skills/hsua80nykz7u/

' 12. http://www.swiftintech.com/ecourses/essential-skills/msexcel-skills/

' 13. http://www.swiftintech.com/ecourses/essential-skills/msword-skills/

' 14. http://www.swiftintech.com/ecourses/nbsa-sil/customerservice-skills/

' 15. http://www.swiftintech.com/ecourses/nbsa-sil/businesscommunications/

' 16. http://www.swiftintech.com/ecourses/nbsa-sil/interpersonal-communication/

' 17. http://www.swiftintech.com/ecourses/nbsa-sil/marketing-fundamentals/

' 18. http://www.swiftintech.com/ecourses/nbsa-sil/selling-techniques/

' 19. http://www.swiftintech.com/ecourses/nbsa-sil/time-priority-management/

' 20. http://www.swiftintech.com/ecourses/nbsa-sil/greenindustries/

' 21. http://www.swiftintech.com/ecourses/life-skills/living-with-technology/

' 22. http://www.swiftintech.com/ecourses/life-skills/money-management1/

' 23. http://www.swiftintech.com/ecourses/life-skills/money-management2/

' 24. http://www.swiftintech.com/ecourses/life-skills/personal-health-management/

' 25. http://www.swiftintech.com/ecourses/life-skills/employability-job-readiness2/

' 26. http://www.swiftintech.com/ecourses/life-skills/employability-job-readiness1/

' 27. http://www.swiftintech.com/ecourses/essential-skills/jobsearch-skills/

' 28. http://www.swiftintech.com/ecourses/essential-skills/resume-skills/

' 29. http://www.swiftintech.com/ecourses/essential-skills/interview-skills/

' 30. http://www.swiftintech.com/ecourses/nbsa-sil/telework-fundamentals/

**Comment by farhany** [comment]
Completed. 

Bonus: Moved ecourses inside of git for better version control and/or boo-boos. And reduction of duplication of work on prod01. Now it just needs to be done on prod00, and prod01 will pick it up.
