### ISSUE TITLE
Updates to EW JobReady Resources Page

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#51]
<b>Pre-requisite Ticket:</b> #48 

![resourcespageupdates](https://cloud.githubusercontent.com/assets/7306437/11772604/0460874e-a1ec-11e5-99dd-7bb07f187c9b.gif)

<b>After ticket #48 has been completed</b>, could we please make the following updates to the EW JobReady System Resources page:

<b>A. Text Change:</b>

Could you please change "Courses from NBSA:" to:

"Courses from the National Institute of Continuing Education:"

---

<b>B1.</b> For the "Request a Course" link description which displays when the blue question mark is clicked, could you please change it from "Clicking here will allow you to request any course from within the NBSA or Skill Improvement Course Libraries."

TO:

"Clicking here will allow you to write to us for additional assistance in the event you cannot find a particular course."

---

<b>B2.</b> Could you please change the "Request a Course" link caption to:

"Get help finding a Course"

---

<b>B3.</b> For the "Search for a Course" link description which displays when the blue question mark is clicked, could you please change it from "Clicking here will allow you to search for any course from within the NBSA or Skill Improvement Course Libraries."

TO: 

"Clicking here will list all the courses found within the Skill Improvement Course Library.

---

<b>C1.</b>For the "Course Catalog" link description which displays when the blue question mark is clicked, could you please change it from "Clicking here will give you access to a catalog containing all the course descriptions from the NBSA and the Skill Improvement Course Library."

TO:

"Clicking here will give you access to a catalog containing the descriptions for all the courses found within the Skill Improvement Course Library as well as courses published by the National Institute of Continuing Education."

---

<b>C2.</b>For the "Certification Catalog" link description which displays when the blue question mark is clicked, could you please change it from "Clicking here will give you access to the NBSA Certification Catalog."

TO:

"Clicking here will give you access to a catalog containing all the required assessments and associated courses for the respective job skill certifications available from the National Institute of Continuing Education."

---

<b>D1.</b> Could you please update the URL that the "Course Catalog" link points to so that it goes to: http://national-certificates.com/coursecatalog

---

<b>D2.</b> Could you please update the URL that the "Certification Catalog" link points to so that it goes to: http://national-certificates.com/certcatalog

**Comment by farhany** [comment]
Completed.
