### ISSUE TITLE
EW JobReady User Resources Page - URL Switch for 1 Link

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#52]
I should have asked this on ticket #51 yesterday. Sorry.

http://ew.swiftintech.com/resources.html

On the EW JobReady Resources Page, for the link caption "Get help finding a Course", could you please change the URL that appears in the pop-up window from:

http://ew.swiftintech.com/tt/fe/main/request_course_form

TO:

http://ewjobready.com/get-help-finding-a-course.html

**Comment by farhany** [comment]
Completed.
