### ISSUE TITLE
NCOA User Resources Page - Text and Link Updates

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#53]
<b>Demo User Access Details</b>

' 1. Go to http://jobsourcencoa.com

' 2. Click Agree. Click User Login. Enter Username: jajatest

' 3. Enter Password: abcdefg

' 4. Click the Resources tab.

<b>Resource Page Updates</b>

http://ncoa.swiftintech.com/resources.html

![ncoa-resources-page-v2](https://cloud.githubusercontent.com/assets/7306437/13911394/33af8fce-ef06-11e5-8a47-9a8c5d4e3b25.gif)

' 1. Could you please change "NBSA" to "National Institute of Continuing Education"

---

' 2. When the question mark is clicked for "Course Catalog", could you please change the displaying text from:

"Clicking here will give you access to a catalog containing all the course descriptions from the NBSA and the Skill Improvement Course Libraries."

TO:

"Clicking here will give you access to a catalog containing the descriptions for all the courses found within the Skill Improvement Course Library as well as courses published by the National Institute of Continuing Education."

---

' 3. When the question mark is clicked for "Certification Catalog", could you please change the displaying text from:

"Clicking here will give you access to the NBSA Certification Catalog."

TO:

"Clicking here will give you access to a catalog containing all the required assessments and associated courses for the respective job skill certifications available from the National Institute of Continuing Education."

---

' 4. When the question mark is clicked for the "Search for a Course" link, could you please change the text that displays from:

"Clicking here will allow you to search for any course from within the Skill Improvement Course Library."

TO:

"Clicking here will list all the courses found within the Skill Improvement Course Library."

---

**Comment by msleeth2** [comment]
If you have some time this month and you can address this ticket. If not...no problem. Maybe next month. Up to you.

**Comment by msleeth2** [comment]
I simplified this ticket down to just the text and link updates needed on the National Council on Aging (NCOA) User Environment "Resources" page. A demo user for this site is:

Go to http://jobsourcencoa.com, click Agree, click User Login, enter jajatest for username and abcdefg for password. Then click Resources.

If you have a chance to get this ticket done by the end of the month, that would be great...just because this client is set to renew in April and I'd like to highlight these site updates to them when I contact them before month end. If you can't, no problem. Next month is fine.

**Comment by farhany** [comment]
Completed.

**Comment by msleeth2** [comment]
Fantastic - thanks!
