### ISSUE TITLE
Upload NICE branded Essential Customer Service Skills Course Files

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#55]
http://www.swiftintech.com/ecourses/essential-skills/customerservice-skills/

Could you please:

a) Unzip the ZIP file located at the below URL and upload all the files to the above directory:

https://esscustskills88x.s3.amazonaws.com/Ess-Customer-Skills.zip

b) Upload the 2 PDF files accessible via the below URLs to the above directory:

https://esscustskills88x.s3.amazonaws.com/Essential-Customer-Service-Skills.pdf

https://esscustskills88x.s3.amazonaws.com/Essential-Customer-Service-Skills-SL.pdf

**Comment by farhany** [comment]
Completed. Unzipped Ess-Customer-Skills.zip to /customerservice-skills/, and added two PDFs there.

Let me know if there is any issue with folder structure.

**Comment by msleeth2** [comment]
Sorry, I'm getting an error message:

Sorry, the document, /ecourses/essential-skills/customerservice-skills/Essential-Customer-Service-Skills.pdf, could not be found. 

This type of message occurs for the online course files from the ZIP file and for the 2 PDFs.

**Comment by farhany** [comment]
Move under essential-skills/customerservice-skills/. Should be fine now. Confirm pls.

**Comment by msleeth2** [comment]
Works great. Thanks!
