### ISSUE TITLE
Upload NICE branded Essential Computer Skills Course Files

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#56]
http://www.swiftintech.com/ecourses/essential-skills/computer-skills/

Could you please:

a) Unzip the ZIP file located at the below URL and upload all the files to the above directory:

https://esscomputerskills7x.s3.amazonaws.com/EssComputerSkills.zip

b) Upload the 2 PDF files accessible via the below URLs to the above directory:

https://esscomputerskills7x.s3.amazonaws.com/Essential-Computer-Skills-SL.pdf

https://esscomputerskills7x.s3.amazonaws.com/Essential-Computer-Skills.pdf

**Comment by farhany** [comment]
Done.

**Comment by msleeth2** [comment]
Thanks!
