### ISSUE TITLE
Upload NICE branded Telwork Fundamentals Course Files

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#57]
http://www.swiftintech.com/ecourses/nbsa-sil/telework-fundamentals/

Could you please:

a) Unzip the ZIP file located at the below URL and upload all the files to the above directory:

https://teleworkfunx9x.s3.amazonaws.com/Telework-Fundamentals.zip

b) Upload the 2 PDF files accessible via the below URLs to the above directory:

https://teleworkfunx9x.s3.amazonaws.com/Telework-Fundamentals.pdf

https://teleworkfunx9x.s3.amazonaws.com/Telework-Fundamentals-SL.pdf

**Comment by msleeth2** [comment]
Going to put this ticket on hold for the time being. Thanks!

**Comment by farhany** [comment]
Complete

**Comment by msleeth2** [comment]
Links work fine. Ticket Closed. Thanks!
