### ISSUE TITLE
Upload NICE branded Essential Office Skills Course Files

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#58]
http://www.swiftintech.com/ecourses/essential-skills/office-skills/

Could you please:

a) Unzip the ZIP file located at the below URL and upload all the files to the above directory:

https://essoffskilv4x.s3.amazonaws.com/EssOfficeSkills.zip

b) Upload the 2 PDF files accessible via the below URLs to the above directory:

https://essoffskilv4x.s3.amazonaws.com/Essential-Office-Skills-SL.pdf

https://essoffskilv4x.s3.amazonaws.com/Essential-Office-Skills.pdf

**Comment by farhany** [comment]
Done

**Comment by msleeth2** [comment]
Sorry, I get an error message:

Sorry, the document, /ecourses/essential-skills/office-skills/Essential-Office-Skills-SL.pdf, could not be found.

**Comment by farhany** [comment]
Moved under essential skills dir. Closing. Check, and re-open if still an issue.

**Comment by msleeth2** [comment]
NP, all the links work correctly now. Much thanks!
