### ISSUE TITLE
Upload NICE branded MS Word Fundamentals Course Files

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#59]
http://www.swiftintech.com/ecourses/essential-skills/msword-skills/

Could you please:

a) Unzip the ZIP file located at the below URL and upload all the files to the above directory:

https://mswordfund4x.s3.amazonaws.com/MS-Word-Fundamentals.zip

b) Upload the 2 PDF files accessible via the below URLs to the above directory:

https://mswordfund4x.s3.amazonaws.com/MS-Word-Fundamentals.pdf

https://mswordfund4x.s3.amazonaws.com/MS-Word-Fundamentals-SL.pdf

**Comment by farhany** [comment]
Completed.

**Comment by msleeth2** [comment]
Links work fine. Thanks!
