### ISSUE TITLE
Upload Course Files for Effective Business Communication Skills

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#60]
http://www.swiftintech.com/ecourses/nbsa-sil/businesscommunications/

Could you please:

a) Unzip the ZIP file located at the below URL and upload all the files to the above directory:

https://ebcnicejan29x3.s3.amazonaws.com/Effective-Business-Communications.zip

b) Upload the 2 PDF files accessible via the below URLs to the above directory:

https://ebcnicejan29x3.s3.amazonaws.com/Effective-Business-Communications.pdf

https://ebcnicejan29x3.s3.amazonaws.com/Effective-Business-Communications-SL.pdf

**Comment by msleeth2** [comment]
Sorry, interestingly enough, Experience Works is asking for this one to be uploaded as a priority above others (which I will be filing tickets for soon). Any chance this can be done by Monday?

**Comment by farhany** [comment]
Completed.

**Comment by msleeth2** [comment]
Thanks! Links work!
