### ISSUE TITLE
Upload Course Files for Green Industries and Occupations

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#61]
http://www.swiftintech.com/ecourses/nbsa-sil/greenindustries/

Could you please:

a) Unzip the ZIP file located at the below URL and upload all the files to the above directory:

https://greenoccs99x.s3.amazonaws.com/GreenOccupations.zip

b) Upload 1 PDF file accessible via the below URL to the above directory:

https://greenoccs99x.s3.amazonaws.com/Green-Industries-Occupations-SL.pdf

**Comment by farhany** [comment]
Complete. This time, everything's should be in the right dirs.

**Comment by msleeth2** [comment]
Thanks, works fine!
