### ISSUE TITLE
Upload Course Files for Interpersonal and Teamwork Skills

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#62]
http://www.swiftintech.com/ecourses/essential-skills/interpersonal-skills/

Could you please upload the 2 PDF files accessible via the below URLs to the above directory:

https://nicecoursefiles98x.s3.amazonaws.com/Interpersonal-And-Teamwork-Skills-SL.pdf

https://nicecoursefiles98x.s3.amazonaws.com/Interpersonal-And-Teamwork-Skills.pdf

**Comment by farhany** [comment]
Completed.

**Comment by msleeth2** [comment]
Thanks!
