### ISSUE TITLE
Upload Course Files for Medical Office Skills

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#63]
http://www.swiftintech.com/ecourses/essential-skills/medicaloffice-skills/

Could you please upload the 2 PDF files accessible via the below URLs to the above directory:

https://nicecoursefiles98x.s3.amazonaws.com/Essential-Medical-Office-Skills-SL.pdf

https://nicecoursefiles98x.s3.amazonaws.com/Essential-Medical-Office-Skills.pdf

**Comment by farhany** [comment]
Complete.
