### ISSUE TITLE
Upload Course Files for Reading and Comprehension Skills

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#64]
http://www.swiftintech.com/ecourses/essential-skills/reading-skills/

Could you please upload the 2 PDF files accessible via the below URLs to the above directory:

https://nicecoursefiles98x.s3.amazonaws.com/Essential-Reading-Comprehension-Skills-SL.pdf

https://nicecoursefiles98x.s3.amazonaws.com/Essential-Reading-Comprehension-Skills.pdf

**Comment by farhany** [comment]
Complete
