### ISSUE TITLE
Upload Course Files for Essential Sales Skills

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#65]
http://www.swiftintech.com/ecourses/essential-skills/sales-skills/

Could you please upload the 2 PDF files accessible via the below URLs to the above directory:

https://nicecoursefiles98x.s3.amazonaws.com/Essential-Sales-Skills-SL.pdf

https://nicecoursefiles98x.s3.amazonaws.com/Essential-Sales-Skills.pdf

**Comment by farhany** [comment]
Complete
