### ISSUE TITLE
Upload Course Files for Essential Telephone Skills

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#66]
http://www.swiftintech.com/ecourses/essential-skills/telephone-skills/

Could you please upload the 2 PDF files accessible via the below URLs to the above directory:

https://nicecoursefiles98x.s3.amazonaws.com/Essential-Telephone-Skills-SL.pdf

https://nicecoursefiles98x.s3.amazonaws.com/Essential-Telephone-Skills.pdf

**Comment by farhany** [comment]
Complete
