### ISSUE TITLE
Upload Course Files for Money Management Fundamentals - Part 1

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#67]
http://www.swiftintech.com/ecourses/life-skills/money-management1/

Could you please upload the 2 PDF files accessible via the below URLs to the above directory:

https://nicecoursefiles98x.s3.amazonaws.com/Money-Management-Fundamentals-P1.pdf

https://nicecoursefiles98x.s3.amazonaws.com/Money-Management-Fundamentals-P1-SL.pdf

**Comment by farhany** [comment]
Complete
