### ISSUE TITLE
Upload Course Files for Money Management Fundamentals - Part 2

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#68]
http://www.swiftintech.com/ecourses/life-skills/money-management2/

Could you please upload the 2 PDF files accessible via the below URLs to the above directory:

https://nicecoursefiles98x.s3.amazonaws.com/Money-Management-Fundamentals-P2.pdf

https://nicecoursefiles98x.s3.amazonaws.com/Money-Management-Fundamentals-P2-SL.pdf

**Comment by farhany** [comment]
Complete
