### ISSUE TITLE
Upload Course Files for Personal and Health Management

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#69]
http://www.swiftintech.com/ecourses/life-skills/personal-health-management/

Could you please upload the 2 PDF files accessible via the below URLs to the above directory:

https://nicecoursefiles98x.s3.amazonaws.com/Personal-Health-Management-SL.pdf

https://nicecoursefiles98x.s3.amazonaws.com/Personal-Health-Management.pdf

**Comment by farhany** [comment]
There are files here already, did you want me to remove data/ and player/ folders or just add the PDFs? For now, I've added the PDFs. Let me know.

**Comment by msleeth2** [comment]
Thanks for letting me know. The PDFs just added can stay of course but the "data" and "player" folders in this directory should be deleted because those contain the old NBSA materials.
