### ISSUE TITLE
Upload Course Files for Essential Bookkeeping Skills

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#70]
http://www.swiftintech.com/ecourses/essential-skills/bookkeeping-skills/

Could you please upload the 2 PDF files accessible via the below URLs to the above directory:

https://nicecoursefiles98x.s3.amazonaws.com/Essential-Bookkeeping-Skills-SL.pdf

https://nicecoursefiles98x.s3.amazonaws.com/Essential-Bookkeeping-Skills.pdf

**Comment by farhany** [comment]
Done

**Comment by msleeth2** [comment]
Thanks!
