### ISSUE TITLE
Upload Course Files for Essential Math Skills

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#71]
http://www.swiftintech.com/ecourses/essential-skills/math-skills/

Could you please upload the 2 PDF files accessible via the below URLs to the above directory:

https://nicecoursefiles98x.s3.amazonaws.com/Essential-Math-Skills-SL.pdf

https://nicecoursefiles98x.s3.amazonaws.com/Essential-Math-Skills.pdf

**Comment by farhany** [comment]
Done
