### ISSUE TITLE
Upload Course Files for Resume Fundamentals

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#72]
http://www.swiftintech.com/ecourses/essential-skills/resume-skills/

Could you please:

a) Unzip the ZIP file located at the below URL and upload all the files to the above directory:

https://resumefund3x.s3.amazonaws.com/Resume-Fundamentals.zip

b) Upload 2 PDF files accessible via the below URLs to the above directory:

https://resumefund3x.s3.amazonaws.com/Resume-Fundamentals-SL.pdf

https://resumefund3x.s3.amazonaws.com/Resume-Fundamentals.pdf

**Comment by farhany** [comment]
Done
