### ISSUE TITLE
Upload Course Files for Time and Priority Management

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#73]
http://www.swiftintech.com/ecourses/nbsa-sil/time-priority-management/

Could you please:

a) Unzip the ZIP file located at the below URL and upload all the files to the above directory:

https://timemgmt5x.s3.amazonaws.com/Time-And-Priority-Mgmt-Skills.zip

b) Upload 2 PDF files accessible via the below URL to the above directory:

https://timemgmt5x.s3.amazonaws.com/Time-and-Priority-Management-SL.pdf

https://timemgmt5x.s3.amazonaws.com/Time-and-Priority-Management.pdf

**Comment by farhany** [comment]
Done
