### ISSUE TITLE
Upload Course Files for Essential Reasoning Skills

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#74]
http://www.swiftintech.com/ecourses/essential-skills/reasoning-skills/

Could you please upload 2 PDF files accessible via the below URL to the above directory:

https://nicecoursefiles98x.s3.amazonaws.com/Essential-Reasoning-Skills-SL.pdf

https://nicecoursefiles98x.s3.amazonaws.com/Essential-Reasoning-Skills.pdf

**Comment by farhany** [comment]
Done
