### ISSUE TITLE
Upload Course Files for Essential Time Management Skills

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#75]
http://www.swiftintech.com/ecourses_open/essential-skills/hsua80nykz7u/

Could you please upload 2 PDF files accessible via the below URL to the above directory (Yup, I know the directory has a weird name ;P):

https://nicecoursefiles98x.s3.amazonaws.com/Essential-Time-Management-SL.pdf

https://nicecoursefiles98x.s3.amazonaws.com/Essential-Time-Management.pdf

**Comment by farhany** [comment]
Done
