### ISSUE TITLE
Upload Course Files for Living with Technology

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#77]
http://www.swiftintech.com/ecourses/life-skills/living-with-technology/

Could you please upload the below PDF files accessible via the below URLs to the above directory:

https://nicecoursefiles98x.s3.amazonaws.com/Living-with-Technology-SL.pdf

https://nicecoursefiles98x.s3.amazonaws.com/Living-with-Technology.pdf

**Comment by farhany** [comment]
Can't find those two PDFs to download. Skipping...

**Comment by msleeth2** [comment]
Sorry. I had not updated the Access Control Layer for these files in my Amazon S3 bucket for some reason. I tested the links out and they now work.

**Comment by farhany** [comment]
Completed.

**Comment by msleeth2** [comment]
All the outstanding course file upload tickets are now complete. 

The only ones left will be the online versions of the courses that I'll be publishing over the coming weeks and months throughout 2016....one by one every 2-3 weeks hopefully....depending on how things go with this SWIFT acquisition thing. There are 22 more courses to go.

Thanks for all your hard work to get these outstanding course file uploads complete. Experience Works will be happy. :)
