### ISSUE TITLE
Upload Course Files for Job Search Fundamentals

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#78]
http://www.swiftintech.com/ecourses/essential-skills/jobsearch-skills/

Could you please upload the below PDF files accessible via the below URLs to the above directory:

https://nicecoursefiles98x.s3.amazonaws.com/Job-Search-Fundamentals-SL.pdf

https://nicecoursefiles98x.s3.amazonaws.com/Job-Search-Fundamentals.pdf

**Comment by farhany** [comment]
Done
