### ISSUE TITLE
Upload Course Files for Entering the Workforce

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#80]
http://www.swiftintech.com/ecourses/life-skills/employability-job-readiness2/

Could you please upload the below PDF files accessible via the below URLs to the above directory:

https://nicecoursefiles98x.s3.amazonaws.com/Entering-the-Workforce-SL.pdf

https://nicecoursefiles98x.s3.amazonaws.com/Entering-the-Workforce.pdf

**Comment by farhany** [comment]
Done
