### ISSUE TITLE
Upload Course Files for Interviewing Fundamentals

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#81]
http://www.swiftintech.com/ecourses/essential-skills/interview-skills/

Could you please upload the below PDF files accessible via the below URLs to the above directory:

https://nicecoursefiles98x.s3.amazonaws.com/Interviewing-Fundamentals-SL.pdf

https://nicecoursefiles98x.s3.amazonaws.com/Interviewing-Fundamentals.pdf

**Comment by farhany** [comment]
Done
