### ISSUE TITLE
Upload Course Files for Selling Techniques

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#82]
http://www.swiftintech.com/ecourses/nbsa-sil/selling-techniques/

Could you please upload the below PDF files accessible via the below URLs to the above directory:

https://nicecoursefiles98x.s3.amazonaws.com/Selling-Techniques-SL.pdf

https://nicecoursefiles98x.s3.amazonaws.com/Selling-Techniques.pdf

**Comment by farhany** [comment]
Done
