### ISSUE TITLE
Upload Course Files for Marketing Fundamentals

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#83]
http://www.swiftintech.com/ecourses/nbsa-sil/marketing-fundamentals/

Could you please upload the below PDF files accessible via the below URLs to the above directory:

https://nicecoursefiles98x.s3.amazonaws.com/Marketing-Fundamentals-SL.pdf

https://nicecoursefiles98x.s3.amazonaws.com/Marketing-Fundamentals.pdf

**Comment by farhany** [comment]
Done
