### ISSUE TITLE
Upload Course Files for "Advanced" Customer Service Skills

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#84]
http://www.swiftintech.com/ecourses/nbsa-sil/customerservice-skills/

Could you please upload the below PDF files accessible via the below URLs to the above directory:

https://nicecoursefiles98x.s3.amazonaws.com/Customer-Service-Skills-SL.pdf

https://nicecoursefiles98x.s3.amazonaws.com/Customer-Service-Skills.pdf

**Comment by farhany** [comment]
Done
