### ISSUE TITLE
Upload Course Files for Interpersonal Communication

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#85]
http://www.swiftintech.com/ecourses/nbsa-sil/interpersonal-communication/

Could you please upload the below PDF files accessible via the below URLs to the above directory:

https://nicecoursefiles98x.s3.amazonaws.com/Interpersonal-Communication-SL.pdf

https://nicecoursefiles98x.s3.amazonaws.com/Interpersonal-Communication.pdf

**Comment by farhany** [comment]
Done
