### ISSUE TITLE
EW JobReady System "Help" Nav Menu URL Update

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#86]
http://ew.swiftintech.com/tt/fe/main/dashboard

On EW JobReady, for the "Help" navigation menu item, could you please change the URL that loads in the new pop-up window when this item is clicked?

![ew-help](https://cloud.githubusercontent.com/assets/7306437/13239958/3fb484f6-d9ac-11e5-8822-a15ec4523218.png)

Currently, the URL that loads in the new pop-up window is:

http://ewhelpsystem4dx.s3.amazonaws.com/engage.swf

Could you please change it to load the following URL instead:

https://ewhelpsystem4dx.s3.amazonaws.com/interaction.swf

For testing purposes, to access the JobReady system as a user, go to http://ewjobready.com, click User Login, enter **jajatest** for user name and **abcdefg** for password.

**Comment by farhany** [comment]
Completed.

**Comment by msleeth2** [comment]
Thanks!

**Comment by msleeth2** [comment]
My bad.

I actually specified the wrong file name extension in the new URL path. Specified .swf instead of html.

As a result, the links don't work in this module that displays in the pop-up window. When you get a chance, no rush, but could you please change the new URL that loads to be:

https://ewhelpsystem4dx.s3.amazonaws.com/interaction.html

**Comment by farhany** [comment]
Completed

**Comment by msleeth2** [comment]
Thanks!
