### ISSUE TITLE
Create Directory - Upload Files - for Essential Time Management Skills Course

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#88]
The request for this ticket is found below the background info section I will lay out here:

<b>Background Info for what I need done:</b>

Thank you for all the course file uploads. It has helped the "Course Access Report" start showing course access records for 29 of 32 courses we have and this is a big relief to the Experience Works client. 

![courseaccessreport](https://cloud.githubusercontent.com/assets/7306437/13827532/699e5cd0-eb93-11e5-914d-266907e9a22a.png)

We still have 3 courses to address: "Living with Technology" (see ticket #77), "Library Fundamentals" (I have not filed the ticket yet) and "Essential Time Management Skills" (see now closed ticket #75).

This new ticket is meant to address what is needed to resolve the issue with the "Essential Time Management Skills" course.

For another course that is working OK, as per ticket #74, you uploaded 2 PDF files for the course "Essential Reasoning Skills" and as you can see from the above screen shot, the course access records show up. You of course uploaded those files to the following directory:

http://www.swiftintech.com/ecourses/essential-skills/reasoning-skills/

However, as per ticket #75, as mentioned in that ticket we had a weird directory for the "Essential Time Management Skills" course. I'm not going to make sense of why it was setup as that directory back in the day but whatever the case, course access records are not showing up for that course. So I think to properly address this, we need to start from scratch and create a new directory for this course that coincides with the directory naming conventions for other working courses. We can basically treat this as we would a "new course" that is to published for new subject material in future.

<b>The Requests for this ticket:</b>

A. Could you please create a new folder in the "essential-skills" directory with the caption "time-mgmt" - i.e.

http://www.swiftintech.com/ecourses/essential-skills/time-mgmt/

B. Could you please upload the 2 PDF files accessible via the below URLs to the above new directory folder you create:

https://nicecoursefiles98x.s3.amazonaws.com/Essential-Time-Management-SL.pdf

https://nicecoursefiles98x.s3.amazonaws.com/Essential-Time-Management.pdf

Hopefully doing this will enable accesses to these course files showing up in the Course Access Report.

**Comment by farhany** [comment]
Created essential-skills/time-mgmt with content:
Essential-Time-Management-SL.pdf  
Essential-Time-Management.pdf

Hopefully that's what you wanted.

**Comment by msleeth2** [comment]
Yup. Works great. Access records show OK in Course Access Report. Thanks!
