### ISSUE TITLE
Create Directory - Upload File - for Library Assistant Fundamentals Course

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#89]
We've got a course called "Library Assistant Fundamentals" that we've never tracked course access for.

A. Could you please create a new folder in the "nbsa-sil" directory with the caption "library-assistant" - i.e.

http://www.swiftintech.com/ecourses/nbsa-sil/library-assistant/

B. Could you please upload the 1 PDF file accessible via the below URL to the above new directory folder you create:

https://nicecoursefiles98x.s3.amazonaws.com/Library-Assistant-Fundamentals.pdf

Hopefully doing this will help accesses to this course file show up in the Course Access Report.

**Comment by farhany** [comment]
Done

**Comment by msleeth2** [comment]
Amazing! It shows up in the Course Access Report. Thanks!
