### ISSUE TITLE
Uzip and Upload Online/Video Course Files for Money Management Fundamentals - Part 2

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#90]
http://www.swiftintech.com/ecourses/life-skills/money-management2/

Could you please unzip the ZIP file located at the below URL and upload all the files to the above directory:

https://mm2newnice54gx.s3.amazonaws.com/Money-Management-Fundamentals-2.zip

**Comment by farhany** [comment]
Completed

**Comment by msleeth2** [comment]
Thanks!
