### ISSUE TITLE
Upload PDF & Online/Video Course Files for MS Excel Fundamentals - Part 1

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#91]
http://www.swiftintech.com/ecourses/essential-skills/msexcel-skills/

Could you please upload the PDF file located at the below URL to the above directory:

https://nicecoursefiles98x.s3.amazonaws.com/MS_Excel_Fundamentals_P1_DL_v1.pdf

Could you also please unzip the ZIP file located at the below URL and upload all the files to the above directory:

https://msexcelfundamentals5x.s3.amazonaws.com/MS-Excel-Fundamentals-Part-1.zip

**Comment by farhany** [comment]
Done

**Comment by msleeth2** [comment]
Thanks!
