### ISSUE TITLE
"Additional Learning Opportunities" link update on EW JobReady

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#92]
If this could please be completed by the end of May, I'd appreciate it.

http://ew.swiftintech.com/resources.html

![addlearnoppsmodonew](https://cloud.githubusercontent.com/assets/7306437/15156785/a7296ede-16b6-11e6-8c49-857e51068560.png)

In the EW JobReady system on the "Resources" page within the user environment, in the "Useful Resources" section of that page, could you please update the link "Additional Learning Opportunities" so that it loads the following URL in the pop-up window: 

http://addlearnoppsv2x.s3.amazonaws.com/player.html

To get into the user environment to see this yourself, please use the following access details:
1. Go to http://ewjobready.com, click Agree, click User Login.
2. Enter User Name: jajatest
3. Enter Password: abcdefg

**Comment by farhany** [comment]
Completed.

**Comment by msleeth2** [comment]
Thanks!
