### ISSUE TITLE
"Orientation" button URL update within EW JobReady User Environment

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#93]
http://ew.swiftintech.com/tt/fe/

![ewjobreadyorientation](https://cloud.githubusercontent.com/assets/7306437/15158269/19ab292e-16bd-11e6-8673-42037c98e442.png)

Within the user environment of the EW JobReady system, could you please update the URL that loads in the new browser window after the "Orientation" button is clicked. An Orientation button click by the user should now load the following URL:

http://ewjobready.com/orientation-within-system.html

To get into the user environment to see this yourself, please use the following access details:

A. Go to http://ewjobready.com, click Agree, click User Login.

B. Enter User Name: jajatest

C. Enter Password: abcdefg

If this could please be completed at a time convenient for you this month, I'd appreciate it.

**Comment by farhany** [comment]
Completed.

**Comment by msleeth2** [comment]
Thanks!
