### ISSUE TITLE
4 Link Updates on Pre-Login EW JobReady Pages

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#94]
Page: http://ew.admin.swiftintech.com/index.html

![admin-login-page](https://cloud.githubusercontent.com/assets/7306437/15252095/561f81ea-18fa-11e6-9fd2-bbbf4794e031.png)

A. For the "Home" button, could you please change the URL the user is sent to from:

http://ew.nbsalliance.com/index.html

TO:

http://ewjobready.com

---

B. For the "Create Account" button, could you please change the URL the user is sent to from:

http://ew.nbsalliance.com/tt/fe/user/authenticate

TO:

http://ewjobready.com/create-account-page.html

---

Page: http://ew.swiftintech.com/main.html

![jobreadyhomepage-backup](https://cloud.githubusercontent.com/assets/7306437/15252221/d7f8fad4-18fa-11e6-99a7-d66b0d522603.png)

C. For the "Administrator Login" link at the above page, could you please change the URL the user is sent to after the link click from:

http://ew.admin.nbsalliance.com/

TO:

http://ew.admin.swiftintech.com/

---

Page: http://ew.swiftintech.com/

![ew-important-info-page](https://cloud.githubusercontent.com/assets/7306437/15252268/07a07172-18fb-11e6-9bcc-1075204545ef.png)

D. For the "Agree" button at the above page, could you please change the URL the user is sent to after the button click from:

http://ew.swiftintech.com/main.html

TO:

http://ewjobready.com

**Comment by farhany** [comment]
Completed.

**Comment by msleeth2** [comment]
Thanks!
