### ISSUE TITLE
3 Link Updates within EW JobReady User Environment

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#95]
I have 3 link updates in the EW JobReady User Environment that need completing hopefully by the end of the month.

A - "Create Your Own Email Address" link on Create Account Page

Found on this page: http://ew.swiftintech.com/tt/fe/user/authenticate

The link that opens in a new window when "Create Your Own Email Address" is clicked should be changed from:

http://nbsalliance-certificates.com/ew-create-email

TO:

http://ewjobready.com/create-your-own-email-address.html

To get to this page as a user, go to http://ew.swiftintech.com/, click Agree, click Create New Account. Then enter admin ID <b>msleeth2</b> and access key <b>abcdefg</b>. Select any State, California is fine, and any location (e.g. the last one that starts with Z). Click Continue. You'll then see the page:

![create-email](https://cloud.githubusercontent.com/assets/7306437/15346411/f47a84aa-1c85-11e6-96d1-8fbfc5dfddb1.png)

---

B - "Create Your Own Email Address" link on Edit Account Page

Found on this page: http://ew.swiftintech.com/tt/fe/user/edit_account

To get to this page, go to http://ewjobready.com, click Agree, click User Login, use jajatest for user name and abcdefg for password. Click Edit Account.

The link that opens in a new window when "Create Your Own Email Address" is clicked should be changed from:

http://nbsalliance-certificates.com/ew-create-email

TO:

http://ewjobready.com/create-your-own-email-address.html

---

C - The "click here" link on the Community preview page.

To get to this page, go to http://ewjobready.com, click Agree, click User Login, use jajatest for user name and abcdefg for password. Click "Community".

The link that opens in a new window when "click here" is clicked should be changed from:

http://nbsalliance-certificates.com/community

TO:

http://ewjobready.com/community

![communitypreview](https://cloud.githubusercontent.com/assets/7306437/15346624/f032e0fc-1c87-11e6-8bea-1d4dfa176807.png)

**Comment by farhany** [comment]
Completed.

**Comment by msleeth2** [comment]
Thanks!
