### ISSUE TITLE
7 Updates on Pre-Login JobSource Pages

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#96]
http://jobsource.swiftintech.com/

A - http://jobsource.swiftintech.com/

For the "Disagree" button, when clicked, it should send the user to the following web address:

http://beswift.com/

---

B - http://jobsource.swiftintech.com/main.html

For the "Administrator Login" link, when clicked, it should send the user to the following web address:

http://jobsource.admin.swiftintech.com/

![jobsourceadminlogin](https://cloud.githubusercontent.com/assets/7306437/15428811/9e1b6722-1e6b-11e6-9336-77fb7bf92b78.png)

---

http://jobsource.admin.swiftintech.com/

![jobsourceadminloginfields](https://cloud.githubusercontent.com/assets/7306437/15428821/a9454b7c-1e6b-11e6-9c05-08e9ffec3830.png)

C - For the "Home" button/link, when clicked, it should send the user to the following web address:

http://jobsource.swiftintech.com/main.html

---

http://jobsource.admin.swiftintech.com/

D - For the "Create Account" button/link, when clicked, it should send the user to the following web address:

http://jobsource.swiftintech.com/tt/fe/user/authenticate

---

http://jobsource.admin.swiftintech.com/

E - Could you please remove the "Contact Us" button/link

---

http://jobsource.admin.swiftintech.com/tt/be/main/login

![jobsource-al-simple](https://cloud.githubusercontent.com/assets/7306437/15428839/b70c944a-1e6b-11e6-9293-d083cd691d89.png)

F - For the "Home" button/link, when clicked, it should send the user to the following web address:

http://jobsource.swiftintech.com/main.html

---

http://jobsource.admin.swiftintech.com/tt/be/main/login

G - For the "Create Account" button/link, when clicked, it should send the user to the following web address:

http://jobsource.swiftintech.com/tt/fe/user/authenticate

**Comment by farhany** [comment]
Completed. F/G are redundant.

**Comment by msleeth2** [comment]
Thanks so much Farhan!
