### ISSUE TITLE
Upload PDF & Online/Video Course Files for Essential Math Skills - Part 1

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#97]
http://www.swiftintech.com/ecourses/essential-skills/math-skills/

Could you please upload the PDF file located at the below URL to the above directory:

http://essmathp1x9.s3.amazonaws.com/Math_Skills_P1_DL_v1.pdf

Could you also please unzip the ZIP file located at the below URL and upload all the files to the above directory:

http://essmathp1x9.s3.amazonaws.com/essential-math-skills-p1.zip

**Comment by farhany** [comment]
Completed.

**Comment by msleeth2** [comment]
Thank you so much!
