### ISSUE TITLE
Create Directory - Upload Files - for Essential Math Skills Part 2 Course

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#98]
Similar ticket: #89

We've got a separate math skills course called "Essential Math Skills - Part 2" that we've never tracked course access for.

A. Could you please create a new folder in the "essential-skills" directory with the caption "math-skills-part2" - i.e.

http://www.swiftintech.com/ecourses/essential-skills/math-skills-part2/

B. Could you please upload the 1 PDF file accessible via the below URL to the above new directory folder you create:

http://essmathp2x7.s3.amazonaws.com/Essential-Math-Skills_P2_NICE_DL_v1.pdf

C. Could you also please unzip the ZIP file located at the below URL and upload all the files to the above directory:

http://essmathp2x7.s3.amazonaws.com/MathSkills-Part2.zip

**Comment by farhany** [comment]
Completed.

**Comment by msleeth2** [comment]
Thanks!
