### ISSUE TITLE
Uzip and Upload Online/Video Course Files for Interview Fundamentals

### ISSUE THREAD

**Issue by msleeth2** [swiftinnovative/projectkickoff#99]
http://www.swiftintech.com/ecourses/essential-skills/interview-skills/

Could you please unzip the ZIP file located at the below URL and upload all the files to the above directory:

http://intfunda5x.s3.amazonaws.com/InterviewFundamentals.zip

**Comment by farhany** [comment]
Done.

**Comment by msleeth2** [comment]
Thanks so much!
